oppia/oppia

scripts/install_third_party.py
This change should allow the server to start without an HTTP 404 error.
=> Font Awesome update to 4.4.0 and use of archive URL

extensions/interactions/InteractiveMap/InteractiveMap.js, extensions/skins/conversation_v1/Conversation.js, extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
Added numerous fixes to the learner view, such as scrolling the content card to show feedback, fixing the supplement card when it reaches the top of the page, and fixing the width of the supplement card on mobile.
There is still a bug with animation for the supplement card on mobile, I'll try to fix this today.
=> Improved skin experimental changes 2

core/domain/exp_services.py, core/domain/stats_jobs.py, core/domain/stats_jobs_test.py, core/storage/base_model/gae_models.py
@sfederwisch I made some changes to your commit and tested them, they seem to work fine I think. Could you PTAL? If you like them I will merge into develop.
Also is there any specific testing I should do in production to ensure this is WAI? If so can you send me an email with this information?
Thanks!
=> Get state counter exp version

core/templates/dev/head/css/oppia.css, extensions/interactions/Continue/Continue.html, extensions/skins/conversation_v1/player.html
I wanted to leave the background-color styling out of the html however I believe it is getting overridden somewhere.
=> Update color of continue button for new learner view #960

extensions/interactions/MultipleChoiceInput/MultipleChoiceInput.html, extensions/interactions/TextInput/TextInput.html
Not sure if this was the right way to go about this. I'm very open to feedback.
=> Learner text input redesign. Fixes #958

core/templates/dev/head/filtersSpec.js
**This code will break the branch.**
Reason for this is required improvements on the code of Truncate at first line filter. I am not able to run the test cases locally (which is very bad) Let's see it on Travis!
=> Adding Os based test cases for checking the correctness of truncate at first line filter.

extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
I intend to continue exploring options for adding a card height animation as well however I'm currently stuck.  In the meantime this will partially alleviate the issue.
=> Learner response fade in animation #962

.jscsrc, CONTRIBUTING.md, scripts/install_third_party.sh, scripts/pre_commit_linter.py
=> Added pre-commit script that lint javascript files

core/templates/dev/head/app.js, core/templates/dev/head/header_js_libs.html, core/templates/dev/head/player/PlayerServices.js, core/templates/dev/head/player/exploration_player.html, core/tests/karma.conf.js, extensions/skins/conversation_v1/Conversation.js, extensions/skins/conversation_v1/player.html, scripts/install_third_party.py
Fixed popover bug due to upgrade
=> Added touch events for tooltips and upgraded ui-bootstrap from 0.13.0 to 0.13.4

core/templates/dev/head/components/paramChangesEditor.js, core/templates/dev/head/components/param_changes_editor.html, core/templates/dev/head/css/oppia.css, extensions/value_generators/templates/Copier.html
Made param changes fit on one row (except when they're in a list), and other small param changes.
=> Param editor changes

scripts/pre_commit_linter.py
@seanlip as we discussed, autofix is bit unsafe so I have removed the option and added the option to pass folder path to lint whole folder.
Thanks
=> Removed autofix option  and Added option to lint all folder

core/templates/dev/head/components/paramChangesEditor.js, core/templates/dev/head/components/param_changes_editor.html, core/templates/dev/head/css/oppia.css
@amitdeutsch -- PTAL at UI. Thanks!
=> Add drag handles for the parameter change editor.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/forms/form_builder_templates.html, extensions/interactions/CodeRepl/CodeRepl.html, extensions/interactions/MultipleChoiceInput/MultipleChoiceInput.html, extensions/interactions/SetInput/SetInput.html, extensions/interactions/TextInput/TextInput.html, extensions/rich_text_components/Image/Image.html, extensions/skins/conversation_v1/Conversation.js, extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
@seanlip I made a few changes and simplifications to the learner view, the most visible of which was adding conversation bubbles. I simplified avatar behavior as well, and ended up having to edit a lot of interactions because of the way they handled their own margins / etc.
However, I'm sure some of these changes break tests, and I think I've broken something up with the card content animation, and I've removed the card-level feedback since it took up too much space on the card. So overall, can you look at the UI first, and then we can tackle the code health if we decide to move forward with these changes? Thanks!
=> Learner view improvements

extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
Also removed user icon from interaction area and added a missing border radius at the bottom of the card.
=> Added right margin to left card in two-card view

core/templates/dev/head/css/oppia.css, extensions/skins/conversation_v1/Conversation.js, extensions/skins/conversation_v1/static/conversation.css
@amitdeutsch -- not quite sure this is what you wanted. Could you PTAL? The delay time can be changed in MIN_CARD_LOADING_DELAY_SEC, but I'm wondering whether we should also make changes to the loading animation (e.g. all three dots always show, and they pulse instead).
=> Add a 750ms delay to Oppia's response.

core/templates/dev/head/editor/feedback_tab/ThreadDataService.js, core/templates/dev/head/editor/feedback_tab/ThreadDataServiceSpec.js, core/templates/dev/head/editor/feedback_tab/feedback_tab.html
1. Fixed typo in test description
2. Fixed filters on the suggestions and feedback tables to display the correct elements
3. Changed suggestionId property to suggestion_id to match backend design doc
=>  Fixed filters for suggestion and feedback tables. Fixed minor typos.

core/templates/dev/head/editor/feedback_tab/feedback_tab.html
Updated syntax of filters in feedback tabs to match new angular version.
=> Update suggestion and feedback filters for Angular 1.4.7

extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
Fixes positioning issue in #1109
=> Added correct positioning to help cards.

.travis.yml, CONTRIBUTING.md, README.md, core/templates/dev/head/expressions/README.txt, core/tests/gae_suite.py, core/tests/protractor/gadgetEditor.js, core/tests/test_utils.py, scripts/backend_tests.py, scripts/run_backend_tests.sh, scripts/run_e2e_tests.sh, scripts/run_frontend_tests.sh, scripts/run_tests.sh, scripts/setup.sh, static/scripts/README
Fixes #1103.
Note to self: Update wiki pages and send an email to oppia-dev@ once this change is checked in.
=> Make the naming of test scripts consistent.

app.yaml, core/templates/dev/head/header_css_libs.html, gulpfile.js, manifest.json, scripts/build.py, scripts/gulp-start-gae-devserver.js, scripts/install_third_party.py, scripts/install_third_party.sh, scripts/start.sh
+ This commit minify all third party css
+ copy all fonts into one folder
+ created manifest.json which will be used in the future by install third_party
+ started using gulp
@seanlip I have one problem with creating URL for fonts as now the request for ```localhost:8181/font/*``` return 404. And thinking should also environment(whether``` dev``` or ```prod```) should be passed as arg so as to control if ```css``` should be minified in ```dev```.
=> Initial implementation of css optimization

extensions/interactions/SetInput/SetInput.js, extensions/interactions/SetInput/SetInputRulesServiceSpec.js
This commit migrates the Set Input rules to the frontend.
=> Migrate Set Input rules to frontend

extensions/interactions/ImageClickInput/ImageClickInput.js, extensions/interactions/ImageClickInput/ImageClickInputRulesServiceSpec.js
This implements the image click input rules in the frontend.
=> Migrate image click input rules to frontend

scripts/install_third_party.sh, scripts/run_e2e_tests.sh, scripts/run_frontend_tests.sh, scripts/setup.sh
Based on a suggestion by @kahkhang.
=> Check that versions of installed node modules are correct on setup.

core/controllers/profile.py, core/controllers/profile_test.py, core/domain/exp_services.py, core/domain/exp_services_test.py, core/domain/user_jobs_one_off.py, core/domain/user_jobs_one_off_test.py, core/domain/user_services.py, core/storage/user/gae_models.py, scripts/backend_tests.py
also function that lives in exp_services that filters out exploration summaries to be displayed on profile page
=> Add backend functionality for computing the explorations created and edited by each user

core/controllers/base.py, core/templates/dev/head/base.html, core/templates/dev/head/player/PlayerServices.js, extensions/skins/conversation_v1/Conversation.js
@amitdeutsch -- PTAL (at functionality only). The list config can be modified in the admin page.
Thanks!
=> Add initial interstitial card to all explorations.

scripts/install_third_party.sh
New pull request with separate branch, and fixed isses
=> Show message when pip is not found, fix for #1170

extensions/interactions/ItemSelectionInput/ItemSelectionInput.html
@seanlip the item selection interaction had very different margins, colors, and font styles from the multiple choice interaction, so I made them more consistent.
=> Made muti-select look like multiple-choice in item-selection interaction

core/templates/dev/head/footer_js_libs.html, core/templates/dev/head/header_js_libs.html, gulpfile.js, manifest.json, scripts/install_third_party.sh
if we include angular in concatenated file. we had to position third_paty.js at the header of the page and this will block rendering . so i removed angular and placed at the header and leaving the rest at the footer.
=> Oppia js minification

core/controllers/collection_viewer.py, core/controllers/galleries.py, core/templates/dev/head/base.html, core/templates/dev/head/collection_player/collection_node_list_directive.html, core/templates/dev/head/components/explorationSummaryTile.js, core/templates/dev/head/components/exploration_summary_tile.html, core/templates/dev/head/components/ratings.js, core/templates/dev/head/css/oppia.css, core/templates/dev/head/dashboard/my_explorations.html, core/templates/dev/head/filters.js, core/templates/dev/head/filtersSpec.js, core/templates/dev/head/galleries/Gallery.js, core/templates/dev/head/galleries/gallery.html, core/templates/dev/head/player/exploration_player.html, core/templates/dev/head/profile/profile.html, core/tests/protractor/publicationAndGallery.js, core/tests/protractor/richTextComponents.js, core/tests/protractor_utils/gallery.js, extensions/interactions/EndExploration/EndExploration.html, feconf.py
@amitdeutsch -- PTAL? Not meant to be perfect, but hopefully it's better than the status quo.
=> New gallery tiles

core/templates/dev/head/components/ratings.js, core/templates/dev/head/components/ratingsSpec.js
Hi @jacobdavis11 -- just a quick check, is this the only place I should change?
=> Change the minimum number of ratings needed to show an average in the gallery to just 1.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/feedback_tab/FeedbackTab.js, core/templates/dev/head/editor/feedback_tab/ThreadDataService.js, core/templates/dev/head/editor/feedback_tab/ThreadDataServiceSpec.js, core/templates/dev/head/editor/feedback_tab/feedback_tab.html
1. View suggestions button for feedback threads
2. Side-by-side comparison modal for suggestion
3. Accept/reject functionality
=> Suggestions Editor View

extensions/skins/conversation_v1/player.html
Changed button behavior when viewport is narrow
=> Changed button behavior when viewport is narrow

core/controllers/collection_editor.py, core/controllers/collection_editor_test.py, core/templates/dev/head/collection_editor/CollectionEditor.js, core/templates/dev/head/collection_editor/collection_editor.html, feconf.py, main.py, scripts/backend_tests.py
=> Collection Editor UI

scripts/backend_tests.py
It's a bit amusing how simple this change is... :-)
/cc @jacobdavis11
=> Remove the backend test count. Fixes #1238.

extensions/skins/conversation_v1/static/conversation.css
=> Moved help card to bottom right of supplement.

gulpfile.js, manifest.json, scripts/install_third_party.py
Hi @seanlip!,
So i have managed to refine the manifest to have the following structure
```
front/backend/oppiaTools: {
" zip": {some zip dependency},
"tar": {some tar dependency},
"files": {some files dependency}
}
```
following this structure I made it easy to test it has certain download_format(zip,files,tar) it must have certain set of keys.
Any suggestion to make it better are welcome. Thanks
=> Manifest.json refinement and syntax tests

core/templates/dev/head/editor/exploration_editor.html
Fixes issue #1253 adding autofocus to the textarea.
=> Adds autofocus to textarea in Publish Exploration modal

core/templates/dev/head/profile/profile.html
=> Fixes displaying newlines correctly in profile

extensions/interactions/GraphInput/GraphInput.js
As checking for isomorphism is high-cost operation,
first check that two graphs have same degree sequences.
=> Heuristic check for isomorphism for GraphInput

scripts/pre_commit_linter.py
Numpy is now also added to the path, in order to fix an import issue during linting
=> Added parsing of file list to the pre_commit_linter script.

scripts/run_presubmit_checks.sh
=> Pre submit checks

core/templates/dev/head/editor/exploration_editor.html, extensions/interactions/MusicNotesInput/MusicNotesInput.js
=> Fixes Music interaction in preview mode

core/templates/dev/head/header_js_libs.html, manifest.json
=> Fixes Music interaction in mobile

core/templates/dev/head/player/information_card_modal.html
=> Fix precision of average rating to one digit

scripts/pre_commit_linter.py
=> Add parallelization to linters

extensions/interactions/ImageClickInput/ImageClickInput.js
=> Fixes Image region interaction misaligning

scripts/install_third_party.sh, scripts/pre_push_hook.py
Before it couldn't find python2
=> Fix starting of pre_push_hook.py

scripts/pre_push_hook.py
=> Allow pre push hook to correctly handle file names with whitespace

extensions/interactions/CodeRepl/CodeRepl.html, extensions/interactions/CodeRepl/CodeRepl.js
This commits are directed to fix issue 1377.
The idea behind this is to create a new theme to bring required changes in look. and set that theme in editor whenever editor is used by a student.
=> Issue 1377

core/templates/dev/head/app.js, core/templates/dev/head/components/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/galleries/Gallery.js, core/templates/dev/head/galleries/gallery.html, manifest.json
Implement carousel for homepage as mentioned in #1353
=> Home Page Carousel

core/templates/dev/head/admin/admin.html, core/templates/dev/head/base.html, core/templates/dev/head/expressions/evaluator.js, core/templates/dev/head/expressions/evaluatorSpec.js, core/templates/dev/head/expressions/expressionInterpolationService.js, core/templates/dev/head/expressions/expressionSyntaxTree.js, core/templates/dev/head/expressions/typeParser.js, core/templates/dev/head/expressions/typeParserSpec.js
Recreation of other commits to avoid major merge conflicts
=> Parse types of parameter expressions

core/templates/dev/head/galleries/gallery.html
=> Fixes awkward Exploration Card width and height

core/templates/dev/head/galleries/Gallery.js
Merge develop into new-gallery and update `exploration-summary-tile` settings in Gallery.js and gallery.html, and oppia.css
=> Merge develop into new-gallery

core/domain/collection_services.py, core/templates/dev/head/collection_editor/CollectionDetailsDirective.js, core/templates/dev/head/collection_editor/CollectionEditor.js, core/templates/dev/head/collection_editor/CollectionNodeDirective.js, core/templates/dev/head/collection_editor/CollectionSkillsListDirective.js, core/templates/dev/head/collection_editor/collection_details_directive.html, core/templates/dev/head/collection_editor/collection_editor.html, core/templates/dev/head/collection_editor/collection_node_directive.html
Frontend implementation of collection's exploration list editor.
This implementation builds up on the code in #1315 by @BenHenning . The major change involves moving towards the use of a directive in the implementation of the collection's exploration list editor.
=> Collection exploration list editor

core/domain/collection_domain.py, core/domain/collection_services.py, core/domain/collection_services_test.py, core/domain/exp_domain.py, core/domain/exp_jobs_one_off.py, core/domain/exp_jobs_one_off_test.py, core/domain/exp_services.py, core/domain/exp_services_test.py, core/jobs_registry.py, core/storage/collection/gae_models.py, core/storage/exploration/gae_models.py
=> Compute # of commits of each contributors for a Exploration 

core/domain/rte_component_registry_test.py, extensions/rich_text_components/Collapsible/Collapsible.py, extensions/rich_text_components/Image/Image.py, extensions/rich_text_components/Link/Link.py, extensions/rich_text_components/Math/Math.py, extensions/rich_text_components/Tabs/Tabs.py, extensions/rich_text_components/Video/Video.py, extensions/rich_text_components/VideoMp4/VideoMp4.py, extensions/rich_text_components/base.py
Hi @GraceGSy, PTAL. Does this make things easier?
=> Remove explicit data URL strings for RTE component icons.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/exploration_settings.html
=> Fix overlapping buttons in control section of exploration settings.

scripts/release_info.py
=> Added script that collects release relevant information.

scripts/pre_push_hook.py
=> fix issue with 'git push --tags' in pre_push_hook

core/templates/dev/head/components/HtmlSelectDirective.js, core/templates/dev/head/components/html_select_directive.html, core/templates/dev/head/components/rule_editor_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/exploration_editor.html
Branch was created to fix issue:
Multiple-choice options that use HTML don't display correctly in the rule dropdowns #674
=> Add html-select-directive

core/controllers/admin.py, core/controllers/admin_test.py, core/controllers/base.py, core/controllers/collection_viewer_test.py, core/controllers/editor.py, core/controllers/editor_test.py, core/controllers/galleries_test.py, core/controllers/home_test.py, core/controllers/moderator_test.py, core/controllers/reader_test.py, core/domain/collection_services_test.py, core/domain/config_domain.py, core/domain/config_domain_test.py, core/domain/config_services.py, core/domain/email_manager_test.py, core/domain/exp_jobs_one_off_test.py, core/domain/exp_services_test.py, core/domain/recommendations_services_test.py, core/domain/rights_manager_test.py, core/domain/user_jobs_one_off_test.py, core/domain/user_services.py, core/domain/user_services_test.py, core/templates/dev/head/admin/Admin.js, core/templates/dev/head/admin/admin.html, core/tests/protractor_utils/users.js, core/tests/test_utils.py
=> Remove ComputedProperty construct. This speeds up all requests by least 100ms.

core/tests/protractor_utils/editor.js
Fix e2e test errors introduced due to #1477
=> Multiselect dropdown e2e test fix

core/templates/dev/head/components/exploration_summary_tile_directive.html
=> Fix Long usernames overflow in the tooltip gallery

core/templates/dev/head/components/RuleEditorDirective.js
=> Fixes front-end error for Set Input interaction

core/templates/dev/head/components/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
It applies the required changes to change the tiles on small screens as discussed on the issue.
@seanlip Please check :)
=> Fixes Issue #1216

core/controllers/admin_test.py, core/controllers/base_test.py, core/controllers/galleries.py, core/controllers/home_test.py, core/templates/dev/head/admin/admin.html, core/templates/dev/head/dashboard/MyExplorations.js, core/templates/dev/head/side_nav.html, extensions/interactions/EndExploration/EndExploration.html, feconf.py, main.py
Fixes #1533 
1. Server-side redirect based on current login status.
2. Update unit-tests to handle redirection (302)
=> Splash my explorations server redirect

core/templates/dev/head/editor/ExplorationEditor.js
=> [#1575] Bug Fix

scripts/start.sh
Error message if GAE curl download doesn't successfully happen. Fixes #1568
=> Error message if GAE curl download doesn't successfully happen

core/domain/exp_services.py, core/storage/user/gae_models.py, core/storage/user/gae_models_test.py
Also added basic tests for the model which were missing.
#1287
=> Added new fields to EpxlorationUSerDataModel needed for editor autosave.

core/domain/email_jobs_one_off.py, core/domain/email_jobs_one_off_test.py, core/domain/email_manager.py, core/domain/email_manager_test.py, core/jobs_registry.py, core/storage/email/gae_models.py, core/storage/email/gae_models_test.py, feconf.py
Implemented #1416: Guard against sending duplicate emails.
=> Implemented #1416: Guard against sending duplicate emails. 

core/domain/exp_services.py, core/domain/summary_services.py, core/domain/summary_services_test.py, core/domain/user_services.py, core/templates/dev/head/components/ExplorationSummaryTileDirective.js
=> [Fix #1550]

core/templates/dev/head/css/oppia.css, core/templates/dev/head/dashboard/NotificationsDashboard.js, core/templates/dev/head/dashboard/notifications_dashboard.html
This is an attempt to fix Issue #1368 
@seanlip Here are some screenshots:
=> Converted notifications to card rows instead of table layout

core/tests/protractor/editorAndPlayer.js, core/tests/protractor/embedding.js, core/tests/protractor/explorationRating.js, core/tests/protractor/fallbacks.js, core/tests/protractor/gadgetEditor.js, core/tests/protractor/historyTab.js, core/tests/protractor/interactions.js, core/tests/protractor/privileges.js, core/tests/protractor/publicationAndGallery.js, core/tests/protractor/richTextComponents.js, core/tests/protractor/stateEditor.js, core/tests/protractor/userManagement.js
Fix for the issue #1579 
Naming Standard in fileName.js
name: user1_fileName
email: user1@fileName.com
name: user2_fileName
email: user2@fileName.com
=> Protractor tests standard names

core/templates/dev/head/pages/about.html
=> Fixed foundation link on about page.

.travis.yml
Solves Issue #1643 for IRC notifications
=> Modifies TRAVIS to report notifications on IRC

core/templates/dev/head/css/oppia.css, core/templates/dev/head/player/feedback_popup_directive.html
Reduced popup width and text area width to prevent overflowing in learners view feedback layout.
=> Fix for overflow in feedback popup. #1637

core/templates/dev/head/editor/feedback_tab/feedback_tab.html
Modified column grid size to solve the problem with the alignment.
=> Fix for improper alignment of state and status of a card in suggestion thread #1656.

.travis.yml
=> Modified .travis.yml for gitter notifications

core/templates/dev/head/collection_player/collection_node_list_directive.html
=> Pass num_views to collection learner view

core/controllers/collection_editor.py, core/controllers/collection_editor_test.py, core/domain/collection_services.py, core/templates/dev/head/collection_editor/CollectionEditor.js, core/templates/dev/head/collection_editor/collection_editor.html, core/templates/dev/head/domain/collection/CollectionRightsBackendApiService.js
=> Collections should be unpublishable #1564

core/controllers/base.py, core/controllers/editor.py, core/controllers/reader.py, core/templates/dev/head/components/SharingLinksDirective.js, core/templates/dev/head/components/sharing_links_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/ExplorationEditor.js, core/templates/dev/head/editor/exploration_editor.html, core/templates/dev/head/player/LearnerViewBreadcrumb.js, core/templates/dev/head/player/exploration_player.html, core/templates/dev/head/player/information_card_modal.html
@seanlip Please review. Fix for #1613
=> [Fix #1613] Social share links directive

core/templates/dev/head/components/SearchBarDirective.js, core/templates/dev/head/components/search_bar_directive.html
Fixes #1617 
Added unselect all option in both category and language selector in search bar.
=> Add Unselect All option in categories and languages selector in search bar

core/templates/dev/head/components/fallback_editor_directive.html
=> Fallback edit button not working #1688

core/templates/dev/head/components/exploration_summary_tile_directive.html
Modified css for the summary tiles to tweak the design for exploration summary tiles in the gallery.
=> Fix for the notification of number of contributors on exploration summary tiles. #1681.

core/templates/dev/head/base.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/error/error.html, core/templates/dev/head/footer.html, core/templates/dev/head/pages/about.html, core/templates/dev/head/pages/forum.html, core/templates/dev/head/pages/participate.html, core/templates/dev/head/pages/privacy.html, core/templates/dev/head/pages/terms.html, core/templates/dev/head/profile/preferences.html, core/templates/dev/head/profile/profile.html, core/templates/dev/head/profile/signup.html
=> Added a footer to informational pages on the site

core/templates/dev/head/components/exploration_welcome_modal_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/EditorServices.js, core/templates/dev/head/editor/ExplorationEditor.js, core/templates/dev/head/editor/exploration_editor.html
Created and styled a welcome screen for first time editor users only. Also added some changes to the tutorial per the mockups.
=> Creates welcome screen preceding editor tutorial

core/templates/dev/head/player/information_card_modal.html
solved the issue #1678 and improved the view of the model in the learners view.
=> solved issue #1678 , links are not squashed now

scripts/setup.sh
=> Enforce permissions on node_modules/ dir in Vagrant.

extensions/interactions/CodeRepl/CodeRepl.html
Hello, I have fixed the issue #1671 , Now anyone can easily highlight the code and can see it highlighted. Please review this fix and let me know if there is a problem.
Thank You
=> fix issue #1671 , highlighting text can be view now

core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/exploration_editor.html
I have fixed the issue #1676 . Now there is no problem in hovering mouse over discard draft dropdown button.
=> Fix issue #1676 : mouse hover problem solved

core/domain/rule_domain_test.py, extensions/interactions/CodeRepl/CodeRepl.js, extensions/interactions/CodeRepl/CodeReplRulesServiceSpec.js, extensions/rules/code_evaluation.py
=> Add an OutputContains rule to the CodeRepl interaction. #1682

core/templates/dev/head/profile/preferences.html
Modified width of select2-dropdown.
=> Fixes the text field display for preferred languages on preferences page. #1703

core/domain/summary_services_test.py
=> [#1729] Summary services tests

core/templates/dev/head/components/exploration_welcome_modal_directive.html, core/templates/dev/head/components/help_modal_directive.html, core/templates/dev/head/editor/ExplorationEditor.js, core/templates/dev/head/editor/exploration_editor.html
Created a new modal directive for the help button to match the mockup:https://marvelapp.com/103d1ch#10921002
Reused the backend tests created for the welcome modal.
=> Fix #1706: update editor help button action to open modal

core/templates/dev/head/admin/Admin.js, core/templates/dev/head/admin/admin.html, core/templates/dev/head/css/oppia.css, core/tests/protractor_utils/admin.js
Added a navigation bar at the top and categorized the page into activities, jobs, configuration settings and misc.
=> Fix #1712: break admin page into categories, and add a navigation bar.

core/templates/dev/head/editor/exploration_settings.html
=> Update text on editor settings tab; remove visibility toggle.

extensions/value_generators/templates/Copier.html
Added vertical alignment to the span on Copier.html.
=> Fix #1788: Aligns textbox properly on welcome card.

core/templates/dev/head/components/exploration_welcome_modal_directive.html
Updated exploration_welcome_modal_directive.html to fix hovering issues on firefox.
=> Update welcome modal directive to fix hovering issue on firefox.

core/tests/protractor.conf.js, scripts/run_e2e_tests.sh, scripts/setup.sh
- Defined a parameter --suite to perform several e2e tests category wise.
- Added categories to test suites.
=> Fix #1757: Divided e2e tests into full, editor, usermanagement and misc.

.travis.yml, core/tests/protractor.conf.js, scripts/run_e2e_tests.sh
Added different suite parameters to .travis.yml.
=> Fix #1779: Splits e2e tests into separate suites on Travis-CI.

core/templates/dev/head/app.js, core/templates/dev/head/components/RatingDisplayDirective.js, core/templates/dev/head/components/RatingDisplayDirectiveSpec.js, extensions/interactions/MusicNotesInput/MusicNotesInput.js, extensions/interactions/MusicNotesInput/MusicNotesInputSpec.js
/cc @gvishal @BenHenning @maitbayev FYI
=> Improve application performance by disabling debug data.

CONTRIBUTING.md
Added makeapullrequest video series link to CONTRIBUTING.md
=> Update CONTRIBUTING.md: Added makeapullrequest links

core/templates/dev/head/base.js, core/templates/dev/head/baseSpec.js, core/templates/dev/head/exploration_editor/statistics_tab/StatisticsTab.js, core/templates/dev/head/services/utilsService.js, core/templates/dev/head/services/utilsServiceSpec.js
Created `utilsService` for keeping commonly used generic functions at one place.
=> Create utils service on frontend

core/templates/dev/head/components/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
Minor changes on exploration_summary_tile_directive.html for truncation length and title part length.
=> Fix #1860: Elongated exploration summary tiles to adjust longer titles.

core/templates/dev/head/player/ConversationSkinDirective.js, core/templates/dev/head/player/ProgressDotsDirective.js, core/templates/dev/head/player/conversation_skin_directive.html
=> Fix #1816: fix animation single-card to double-card

core/templates/dev/head/forms/formBuilder.js, core/tests/protractor/stateEditor.js, core/tests/protractor_utils/forms.js, extensions/interactions/MultipleChoiceInput/protractor.js
Removes underline button from the toolbar options of textAngular.
=> Remove underline button group from text editor

core/templates/dev/head/css/oppia.css
Modified .oppia-exp-summary-tiles-container in css to fix unnecessary scrolling in exploration.
=> Fix #1881: Reduces unnecessary scrolling in exploration.

Vagrantfile
=> Increase default memory in Vagrantfile to 2048mb

core/controllers/pages.py, core/templates/dev/head/css/oppia.css, core/templates/dev/head/footer.html, core/templates/dev/head/pages/about.html, core/templates/dev/head/pages/contact.html, core/templates/dev/head/pages/teach.html, feconf.py, main.py
Fixes addressed in PR #1892 
@seanlip
=> Fix for PR #1892: About / Teach pages and new Get Involved page

core/templates/dev/head/components/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
@markhalpin PTAL
@amgowano @BenHenning FYI the previous commit (collection summary tiles) broke some of the styling on the library page.
=> Fix merge error in styling of summary tiles that was due to commit 63c7888.

core/controllers/library.py, core/domain/summary_services.py, core/templates/dev/head/components/CollectionSummaryTileDirective.js, extensions/interactions/EndExploration/EndExploration.html, i18n/en.json, i18n/es.json
=> Fix #1971: rename gallery to library (this regressed due to merge issues).

core/templates/dev/head/css/oppia.css, core/templates/dev/head/profile/profile.html
@p4rsec -- I started to file an issue for this, and realized that it really needed a screenshot. Then I started making one, and realized that I'd written the whole thing...
So, I'll suggest a different issue, but please feel free to take a look at this one, and let me know what you think of it! You can check out the PR as follows:
git fetch upstream
git checkout image-hover
and this should allow you to view it on a local server.
Also, assigning to @kevinlee12 for formal review.
=> Add help text for when a user hovers over their image on the profile page.

core/templates/dev/head/components/CreateActivityButtonDirective.js
=> Fix #1983: add activity creation modal duplicate checker

core/templates/dev/head/admin/admin.html, core/templates/dev/head/base.html, core/templates/dev/head/css/oppia.css
/cc @bjvoth -- FYI, I wanted to address this before the upcoming release (hence this PR), but the doc you're working on (with regards to defining the navbar behaviour) is still relevant. Please let us know once you've compiled it!
Assigning to @kevinlee12 for review.
=> Fix parts of navbar dropping off the top of the page on small screens.

extensions/interactions/EndExploration/EndExploration.html, extensions/interactions/EndExploration/EndExploration.js
=> Fix collection name not showing in return to collection button

extensions/interactions/ImageClickInput/ImageClickInput.html, extensions/interactions/InteractiveMap/InteractiveMap.html
Fix #1943, as well as similar issue with ImageClickInput, other interactions works fine.
=> Fix #1943: fixes interactions width on narrow viewport

core/storage/feedback/gae_models.py, core/storage/feedback/gae_models_test.py, feconf.py
- Modifies core/storage/feedback/gae_models.py for adding FeedbackMessageEmailDataModel.
- Modifies feconf.py to add relevent constants, default values for feedback message email service.
Introducing initial patch to start implementation of feedback message email services.
=> Fix #461: introducing milestone #1 for feedback message emails.

queue.yaml
=> Add a task queue for backups.

extensions/rich_text_components/Image/Image.html, extensions/rich_text_components/Image/Image.js, extensions/rich_text_components/Image/Image.py
Added a caption to the angular and python controllers, as well as the html display. This pull request is a clean version of PR# 2024. @AllanYangZhou I have added center styling to the figcaption.
=> Fixes #1931: Adding a caption to RTE image

core/templates/dev/head/exploration_editor/preview_tab/PreviewTab.js, core/templates/dev/head/exploration_editor/preview_tab/preview_tab.html
Fix milestones 3 and 5 of #921:
Add button to restart preview mode from initial state.
Show a list of all current parameter values in preview mode.
=> Fix milestones 3 and 5 of #921: List parameter values in preview and add button to restart preview.

core/templates/dev/head/dashboard/dashboard.html
=> Fix #2117: added span element for creator dashboard text

core/domain/email_manager.py, core/domain/email_manager_test.py, core/templates/dev/head/dashboard/dashboard.html, feconf.py
=> Hotfix dashboard and emails

core/templates/dev/head/css/oppia.css, core/templates/dev/head/exploration_editor/exploration_editor.html
Fix #2017 
Added code from the save draft button to Publish button as well to show the changes made and also increased left padding to accommodate the text and the number.
=> Fix #2017 Update publish button to show changes that are made

core/controllers/cron.py, core/domain/user_jobs_continuous.py, core/domain/user_jobs_one_off.py, core/domain/user_jobs_one_off_test.py, core/domain/user_services.py, core/domain/user_services_test.py, core/storage/user/gae_models.py, feconf.py, main_cron.py, utils.py, utils_test.py
Tasks to be completed as a part of this PR:
=> Fix part of #1366: Cron job to keep history of dashboard statistics

extensions/interactions/EndExploration/EndExploration.html
This PR addresses issue #2116. It was decided to remove the return to collection button altogether.
=> Fix #2116: remove return to collection button

core/templates/dev/head/base.html, core/templates/dev/head/collection_editor/collection_editor.html, core/templates/dev/head/dashboard/dashboard.html, core/templates/dev/head/exploration_editor/exploration_editor.html, core/templates/dev/head/player/exploration_player.html
As discussed in #2272 
@seanlip Please review.
=> Alphabetize and limit GLOBALS to 80 chars in html

core/templates/dev/head/css/oppia.css, core/templates/dev/head/dashboard/dashboard.html
Implemented as discussed in https://github.com/oppia/oppia/issues/2260 
@AllanYangZhou Please review.
=> Fix part of #1366: Display new feedback in creator dasboard

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/about.html
The credit columns in about section are now of equal length.
=> Fix #2277:credit columns are of equal length

app.yaml, feconf.py, scripts/pre_commit_linter.py, scripts/pre_push_hook.py, scripts/start.sh
added documentation about --prod_env flag, MINIFICATION and DEV_MODE variables and added the check for app.yaml for any change in MINIFICATION variable. 
fix #2271.
=> Fix #2271: Add documentation about minification flag and check for bad pattern before committed.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/dashboard/Dashboard.js, core/templates/dev/head/dashboard/dashboard.html
Here's how the dashboard looks when viewed in my phone.
(Ignore yellowish tinge. It's due to a screen filter)
=> Fix #2188: Make current UI of creator dashboard responsive.

core/templates/dev/head/header_css_libs.html
Fix #2302: combine multiple font requests into one.
=> Fix #2302: combine multiple font requests into one.

core/templates/dev/head/dashboard/Dashboard.js
=> Replace usage of default as key name in Dashboard.js

core/controllers/cron.py
=> Fix incorrect docstring.

core/templates/dev/head/app.js, core/templates/dev/head/components/ExplorationCreationService.js, core/templates/dev/head/components/OutcomeDestinationEditorDirective.js, core/templates/dev/head/exploration_editor/EditorServices.js, core/templates/dev/head/exploration_editor/ExplorationEditor.js, core/templates/dev/head/exploration_editor/exploration_editor.html, core/templates/dev/head/exploration_editor/main_tab/StateEditor.js, core/templates/dev/head/exploration_editor/main_tab/StateInteraction.js, core/templates/dev/head/exploration_editor/main_tab/StateResponses.js, core/tests/protractor/editorAndPlayer.js
=> Add analytics events

core/controllers/cron.py, core/controllers/editor_test.py, core/controllers/feedback_test.py, core/controllers/profile.py, core/domain/email_manager.py, core/domain/email_manager_test.py, core/domain/feedback_services.py, core/domain/feedback_services_test.py, core/platform/app_identity/gae_app_identity_services.py, core/platform/email/gae_email_services.py, core/platform/email/gae_email_services_test.py, core/platform/email/mailgun_email_services.py, core/platform/email/mailgun_email_services_test.py, core/platform/models.py, core/templates/dev/head/profile/Signup.js, core/templates/dev/head/profile/signup.html, cron.yaml, feconf.py, scripts/install_third_party.sh
This PR implements mailgun api for sending emails.
=> Fix #2259: Implement mailgun api for sending emails.

scripts/install_prerequisites.sh
Fixes the pyyaml part of #2319.
=> Add pyyaml into install prereqs script

core/templates/dev/head/components/collection_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
Fixes activity tiles alignment in library search.
=> Fix #2244: Fixes activity tiles alignment in library search.

core/templates/dev/head/app.js, core/templates/dev/head/appSpec.js, core/templates/dev/head/exploration_editor/ExplorationEditor.js, core/templates/dev/head/exploration_editor/exploration_editor.html, core/templates/dev/head/exploration_editor/settings_tab/settings_tab.html, core/templates/dev/head/filters.js, extensions/interactions/CodeRepl/CodeRepl.js, extensions/interactions/PencilCodeEditor/PencilCodeEditor.js, extensions/interactions/PencilCodeEditor/PencilCodeEditorRulesServiceSpec.js, extensions/interactions/rules.json
- Revert changes to code normalization logic. Add a new rule for output normalization that is lenient with respect to whitespace and case.
- Fix #2388 and #2392: handle long titles and short objectives correctly.
=> Additional hotfixes to master.

core/templates/dev/head/app.js, core/templates/dev/head/appSpec.js, core/templates/dev/head/exploration_editor/ExplorationEditor.js, core/templates/dev/head/exploration_editor/exploration_editor.html, core/templates/dev/head/exploration_editor/settings_tab/settings_tab.html, core/templates/dev/head/filters.js, extensions/interactions/CodeRepl/CodeRepl.js, extensions/interactions/PencilCodeEditor/PencilCodeEditor.js, extensions/interactions/PencilCodeEditor/PencilCodeEditorRulesServiceSpec.js, extensions/interactions/rules.json
This has already been reviewed, and can be merged when tests pass. DO NOT SQUASH THIS.
=> Additional hotfixes to master. (#2390)

core/templates/dev/head/exploration_editor/ExplorationEditor.js
=> Fixing minor typo in explanatory text

core/templates/dev/head/app.js, core/templates/dev/head/services/explorationServices.js, extensions/interactions/CodeRepl/CodeRepl.js, extensions/interactions/Continue/Continue.js, extensions/interactions/GraphInput/GraphInput.js, extensions/interactions/ImageClickInput/ImageClickInput.js, extensions/interactions/InteractiveMap/InteractiveMap.js, extensions/interactions/ItemSelectionInput/ItemSelectionInput.js, extensions/interactions/LogicProof/LogicProof.js, extensions/interactions/MathExpressionInput/MathExpressionInput.js, extensions/interactions/MultipleChoiceInput/MultipleChoiceInput.js, extensions/interactions/MusicNotesInput/MusicNotesInput.js, extensions/interactions/NumericInput/NumericInput.js, extensions/interactions/PencilCodeEditor/PencilCodeEditor.js, extensions/interactions/SetInput/SetInput.js, extensions/interactions/TextInput/TextInput.js
Before every interaction was calling $scope.$parent.submitAnswer which has some limits.
This PR changes it to a callback.
=> Refactor interaction $scope.$parent.submitAnswer

extensions/interactions/LogicProof/static/js/conversion.js, extensions/interactions/LogicProof/static/js/data.js, extensions/interactions/LogicProof/static/js/teacher.js, extensions/interactions/LogicProof/static/js/tools/demonstration.js, extensions/interactions/LogicProof/static/js/tools/strings.js, extensions/interactions/LogicProof/static/js/tools/teacher2.js, scripts/build.py
Fix #2413: ignore copying python files when generating build directory
/cc @seanlip @BenHenning
=> Fix #2413: ignore copying python files when generating build directory

app.yaml, core/controllers/pages.py, core/templates/dev/head/pages/splash_at2.html, core/templates/dev/head/pages/splash_s4.html
Assigning to:
- @BenHenning for review of instance_type downgrade
- @wxyxinyu for review of splash page backend logic change
@wxyxinyu, can we deploy this once it's merged? Thanks!
=> Minor hotfix: downgrade instance type to F2, add new splash pages.

core/templates/dev/head/player/conversation_skin_directive.html
Remove redundant if-checks in conversation skin template.
=> Small refactor in conversation_skin_directive.html

core/domain/activity_domain.py
This PR Adds docstrings to core/domain/activity_domain.py, part of #2394.
=> Fix #2394: Add docstrings to core/domain/activity_domain.py.

core/templates/dev/head/components/collection_summary_tile_directive.html
@kevinlee12 @amgowano @wxyxinyu would one of you be able to PTAL at this (both code and UI)? The current version, with the tops of the cards not aligned, is kind of messy.
@wxyxinyu is doing a release today, so it'd be nice to get this in for that if possible.
Thanks!
=> Align the tops of the exploration and collection cards on the library page.

core/templates/dev/head/exploration_editor/EditorServices.js, core/templates/dev/head/exploration_editor/ExplorationEditor.js
=> Fix #2242: Alter criteria for showing version mismatch modal when clicked on save changes button.

core/templates/dev/head/collection_editor/editor_tab/collection_main_tab_directive.html, core/templates/dev/head/collection_editor/editor_tab/collection_node_editor_directive.html
=> Fix #2057: improve the display of collection node list editor when there are too many nodes.

core/domain/activity_services.py
The issue adds useful docstrings for the methods which is present in ``activity_services.py``. The Pull request is related to #2394.
=> Fix #2394: Add useful docstrings for activity services methods.

core/domain/exp_services_test.py, core/domain/feedback_services.py, core/domain/feedback_services_test.py
Add docstring for feedback_service.py.
Note: for some obvious arguments I'd rather not put any verbose explanation. The variable name explains everything.
=> Add docstring for feedback_service.py

main.py, main_cron.py, main_taskqueue.py
Fix #1726 .
Generate the field `name` as `regex_route.replace('/', '_')`
=> Fix #1726. Remove the third argument of get_redirect_route in main.py

core/templates/dev/head/dashboard/dashboard.html
=> Fix: #2365 : Add right-clickable fix to dashboard tiles

core/templates/dev/head/collection_editor/editor_tab/collection_node_creator_directive.html
Fix #2029: Modified UI for adding a new exploration in collection to use Twitter bootstrap elements.
=> Improve UI for adding a new exploration in collection

core/templates/dev/head/components/collection_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
Fixes alignment of card icons in collection tile and exploration tiles.
=> Fix #2499 : alignment of card icons

core/domain/rating_services.py
This PR Adds docstrings to core/domain/rating_services.py, part of #2394.
=> Fix #2394: Add docstrings to core/domain/rating_services.py

core/controllers/reader.py, core/domain/activity_domain.py, core/domain/classifier_services.py, core/domain/classifier_services_test.py
I hid some existing part of the class docstring, and added them as comments in the class's __init__ method.
Part of #2394.
=> Updates docstrings in core/domain/classifier_services.py

core/domain/exp_services.py, core/domain/user_jobs_one_off.py, core/domain/user_jobs_one_off_test.py, core/domain/user_services.py, core/domain/user_services_test.py, core/jobs_registry.py, core/storage/user/gae_models.py
Added field in user models to record last time when user edited or created an exploration.
=> Add field to record last exploration created and edited time.

core/templates/dev/head/css/oppia.css
=> Fix #2532.

core/templates/dev/head/pages/dashboard/Dashboard.js
@seanlip @wxyxinyu Please review
=> Fix incorrect ordering of private explorations when sorted by title

scripts/pre_commit_linter.py
https://github.com/oppia/oppia/issues/2357
=> JS lint, don't allow forbidden words in focused tests

core/templates/dev/head/filters.js
Fix #2579 . deletes duplicates in [filters.js](https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/filters.js) .
=> Fix #2597: Delete duplicate angular filters.

core/templates/dev/head/pages/base.html, core/templates/dev/head/pages/footer.html, core/templates/dev/head/pages/privacy/privacy.html, core/templates/dev/head/pages/terms/terms.html, core/tests/protractor.conf.js, core/tests/protractor/staticPagesTour.js, core/tests/protractor_utils/general.js
Related to #2529
Tasks done:
- Add protractor tests
- Fix a JQuery issue by escaping `#`
- Remove unnecessary script in `privacy.html` as there are no quicklinks in `privacy.html`
=> Add protractor tests to visit static pages

core/templates/dev/head/pages/base.html, core/tests/protractor.conf.js, core/tests/protractor/loginFlow.js
Adds protractor tests for logged-in flow.
=> Fix #2529 Add protractor tests for logged-in flow

core/controllers/base.py, core/controllers/base_test.py, core/domain/rights_manager.py, feconf.py
https://github.com/oppia/oppia/issues/2053
=> #2053 Minimize calls to is_admin, static site_name and feedback_url

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/library/Library.js, core/templates/dev/head/pages/library/library.html
Recreated the[ pull request](https://github.com/oppia/oppia/pull/2505) to avoid merge conflicts. @seanlip  Please take a look.
=> Fix #2225: Make library carousel title links more obvious and remove "View All" button

core/templates/dev/head/pages/exploration_player/exploration_player.html
Along with problems in adding math component, there were also certain problems in adding links while suggesting. So fixed that too.
=> Fix #2604: Add Math component while suggesting changes

core/domain/collection_services_test.py, core/domain/exp_services_test.py, core/storage/base_model/gae_models.py, core/storage/feedback/gae_models.py
Add docstrings to gae_models.py. Fixes #2394.
=> Fix #2394: Add docstrings to gae_models.py

core/templates/dev/head/pages/exploration_player/PlayerServices.js, core/templates/dev/head/pages/exploration_player/PlayerTranscriptService.js
Also made a few aesthetic changes to `PlayerTranscriptService`.
=> Fix #2015: Ensure explorations of a single state are properly recorded when completed

core/templates/dev/head/pages/exploration_player/SupplementalCardDirective.js, core/templates/dev/head/pages/exploration_player/supplemental_card_directive.html
This is dirty fix for # #2681, but it also takes care of other corner cases.
=> Fix  #2681: Fix jittering help card at a certain size

core/domain/email_manager.py, core/domain/email_manager_test.py, core/platform/email/gae_email_services.py, core/platform/email/mailgun_email_services.py, core/storage/email/gae_models.py, core/storage/email/gae_models_test.py, feconf.py
Milestone 5 of #2269:
- Added BulkEmailModel to store data regarding to emails which are sent in bulk.
- Added necessary functions to be able to send emails in bulk.
=> Fix part of #2269: Add BulkEmailModel and functionality for sending emails in bulk.

core/tests/protractor/richTextComponents.js, core/tests/protractor/staticPagesTour.js
=> Fix YouTube error in Protractor tests.

core/domain/email_manager.py
Add docstrings to email_manager.py. Fixes part of #2394.
=> Fix #2394: Add docstrings to email_manager.py

core/templates/dev/head/pages/exploration_player/ConversationSkinDirective.js, core/templates/dev/head/pages/exploration_player/SupplementalCardDirective.js, core/templates/dev/head/pages/exploration_player/TutorCardDirective.js, core/templates/dev/head/pages/exploration_player/conversation_skin_directive.html, core/templates/dev/head/pages/exploration_player/conversation_skin_embed_directive.html, core/templates/dev/head/pages/exploration_player/supplemental_card_directive.html, core/templates/dev/head/pages/exploration_player/tutor_card_directive.html
(NB: @maitbayev, I did do an audit, and I think the current state of things is actually pretty reasonable. I made a few small changes in this PR, the largest of which simply reflects that the main directive no longer has an "iframed" mode.)
=> Cosmetic changes to various learner view directives.

.travis.yml
(As discussed during the tech lead meeting.)
=> Remove flaky performance test from the regular Travis build.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/collection_player/collection_player.html
Updated the background for the collection player following #2758 using the new background-banner directive.
=> Change background for collection-player.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/dashboard/dashboard.html
Due to implementation of right-clickability on collection the tiles, the color of the description and other things appeared green instead of black. This PR fixes that.
=> Fix color of description in collections on creator dashboard

core/templates/dev/head/pages/exploration_editor/simple_editor_tab/simple_editor_sidebar_directive.html
It needs more tweaking, it looks like this
=> Initial workd on sidebar: scrollbar.

core/domain/html_cleaner.py
Note: This builds on some (unfinished) work by @souravsingh.
=> Fix part of #2394: add docstrings for html_cleaner.py.

core/templates/dev/head/css/oppia.css
/cc @tjiang11 
(Note: This handles residual comments in #2782.)
=> Fix class names missed during renaming.

core/templates/dev/head/components/top_navigation_bar/top_navigation_bar_directive.html, core/templates/dev/head/css/oppia.css
=> Fix #2787: Eliminate blue outlines on graphic links

core/templates/dev/head/app.js, core/templates/dev/head/directives.js, core/templates/dev/head/pages/exploration_player/ConversationSkinDirective.js, core/templates/dev/head/pages/exploration_player/PlayerConstants.js, core/templates/dev/head/pages/exploration_player/SupplementalCardDirective.js, core/templates/dev/head/pages/exploration_player/TutorCardDirective.js, extensions/rich_text_components/VideoMp4/VideoMp4.js
=> Fix #2686: Fix autofocus issue in player view

core/controllers/email_dashboard.py, core/controllers/email_dashboard_test.py, core/domain/email_manager.py, core/storage/email/gae_models.py, core/templates/dev/head/pages/email_dashboard/EmailDashboardResult.js, core/templates/dev/head/pages/email_dashboard/email_dashboard_result.html, feconf.py, main.py
This PR adds functionality of testing bulk emails before sending them out to qualified users of a query.
=> Fix #2790: Add functionality for testing bulk email prior sending it out.

core/domain/user_services.py
Improve docstrings in Python backend code to follow [Google Python style guide](https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments).
This PR covers the following file(s)
=> Fix part of #2394: Update docstrings to follow the style guide in user_services.py

core/templates/dev/head/pages/base.html
This PR is only a temporary fix for #2855
=> Fix #2855: Replace help text for noscript

core/templates/dev/head/pages/about/about.html
=> Fix part of #2128: Add alt tags to about page

core/templates/dev/head/pages/exploration_player/exploration_footer_directive.html
=> Fix #2800: Make the author profile dropup like the other menus

core/templates/dev/head/pages/exploration_player/conversation_skin_embed_directive.html
=> Fix #2680: fixing the the helper-card positioning

core/domain/subscription_services.py, core/domain/subscription_services_test.py, core/storage/user/gae_models.py
For details on what should be accomplished in this milestone, refer to the design doc [here](https://docs.google.com/document/d/1BkQ3E_ELdp6fs93mgx84TZgpXWaN2_iCO5SoJH3vZKQ/edit?usp=sharing).
=> First milestone of Subscribers Project

assets/images/general/collection_corner.svg, core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/library/Library.js, core/templates/dev/head/pages/library/library.html
I wasn't sure about how to put in the url for the collection-corner image. Should I be using the UrlInterpolationService?
Also, does anyone know what the point of the "title-section-mask" divs are? I deleted some, and left one--but they don't seem to make any noticeable difference regardless.
=> Fix #2801: Change collection style in library and remove shadows from carousel scrolling.

core/templates/dev/head/pages/donate/donate.html, core/templates/dev/head/pages/library/library.html, core/templates/dev/head/pages/splash/splash.html, core/templates/dev/head/pages/splash/splash_ah0.html, core/templates/dev/head/pages/splash/splash_ah1.html, core/templates/dev/head/pages/splash/splash_ah2.html, core/templates/dev/head/pages/splash/splash_ai0.html, core/templates/dev/head/pages/splash/splash_ai1.html, core/templates/dev/head/pages/splash/splash_ai2.html, core/templates/dev/head/pages/splash/splash_ai3.html, core/templates/dev/head/pages/splash/splash_at0.html, core/templates/dev/head/pages/splash/splash_at1.html, core/templates/dev/head/pages/splash/splash_at2.html, core/templates/dev/head/pages/splash/splash_av0.html, core/templates/dev/head/pages/splash/splash_av1.html
=> Fix #2128: Add alt tags to donate, library, and splash pages

core/templates/dev/head/pages/exploration_editor/settings_tab/settings_tab.html, core/tests/protractor.conf.js, core/tests/protractor/parameters.js, core/tests/protractor_utils/editor.js
Created parameters.js to perform e2e testing of parameters/expressions
=> Fix #2251 : e2e test for parameters/expressions

core/templates/dev/head/pages/about/about.html
One additional change from the site copy audit that we didn't address in PR #2793
=> Modified about page headline

core/storage/exploration/gae_models.py
Adds docstring to exploration/gae_models.py. Fixes https://github.com/oppia/oppia/issues/2394
=> Fix #2394: Add Docstrings in exploration/gae_models.py

assets/i18n/en.json, core/templates/dev/head/css/oppia.css
Buttons have been made of uniform width.
=> Fix #2893 : Modify buttons on Teach Widths Are Uniform

core/templates/dev/head/pages/about/about.html
Added two buttons inside the page card which are linked to Donate page and Get Involved page
=> Fix #2816:Add call to action buttons to the Foundation page

AUTHORS
Make the AUTHORS file alphabetically ordered.
=> Fix alphabetical ordering of authors

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/about/about.html, core/templates/dev/head/pages/teach/teach.html
@jaredsilver , can you check if there is some change in spacing needed.
=> Fix #2914 : Improve spacing of buttons on Teach and About pages

assets/i18n/en.json, assets/i18n/hi.json, assets/i18n/qqq.json, core/controllers/profile.py, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/profile/Profile.js, core/templates/dev/head/pages/profile/profile.html
For details on what should be accomplished in fifth milestone, refer to the design doc [here](https://docs.google.com/document/d/1BkQ3E_ELdp6fs93mgx84TZgpXWaN2_iCO5SoJH3vZKQ/edit).
Attached here is a mock for reference -
=> Fix part of #2287: Add subscribe and unsubscribe button to profile of authors

core/storage/user/gae_models.py
Resubmitting PR due to a problem in merging.
=> Fix #2394: Add docstring to core/storage/user/gae_models.py

core/templates/dev/head/pages/splash/splash.html
IMPORTANT NOTE (please read, then delete):
The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: introduce the first version of the collection editor.".
=> Button text size on splash.html

core/storage/email/gae_models.py, scripts/install_third_party.sh, scripts/run_backend_tests.sh, scripts/setup.sh, scripts/setup_gae.sh
=> Docstrings added in the file core/storage/email/gae_models.py

core/storage/collection/gae_models.py
Update docstrings at core/storage/collection/gae_models.py 
- in consistency with the rest of the approved core/storage/* docstrings 
Fixes #2394
=> Fix #2394: Update docstrings in core.storage.collection.gae_models

core/templates/dev/head/components/summary_tile/CollectionSummaryTileDirective.js, core/templates/dev/head/components/summary_tile/ExplorationSummaryTileDirective.js, core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/pages/dashboard/dashboard.html
=> Fix #2918: Fix collection tile in creator dashboard.

core/templates/dev/head/css/oppia.css
@seanlip i have followed the guidlines as mentioned in the instruction of setting up oppia.
=> Fix #2620 : Fix exploration card height and deadzone

core/templates/dev/head/pages/collection_editor/collection_editor.html
Fix #2995 
Added factory dependencies to collection editor.
=> Fix #2995: Add dependencies to collection editor html

scripts/install_third_party.sh
=> Fix #3020: Add -L for curl redirect

extensions/interactions/MathExpressionInput/MathExpressionInput.js
(Hoping to get this in for the release.)
Old version:
New version:
=> Change the default text for MathExpressionInput to 'Type a formula here.'

core/templates/dev/head/pages/base.html, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/collection_player/collection_player.html, core/templates/dev/head/pages/dashboard/dashboard.html, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/library/library.html, core/templates/dev/head/pages/profile/profile.html
This is partial work on  #2099 . with the aim to reduce unnecessary js file in base.html
=> Remove unnecessary js files.

core/domain/exp_services.py
Fix #2394: Add useful docstring to "core/domain/exp_services.py"
=> Added docstring to "core.domain.exp_services"

core/templates/dev/head/pages/collection_player/CollectionPlayer.js
Fix height being undefined if there's 1 collection node, and accessing elements of empty list.
=> Fix some bugs in collection player

core/templates/dev/head/pages/about/about.html, core/templates/dev/head/pages/base.html, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/collection_player/collection_player.html, core/templates/dev/head/pages/contact/contact.html, core/templates/dev/head/pages/dashboard/dashboard.html, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/get_started/get_started.html, core/templates/dev/head/pages/library/library.html, core/templates/dev/head/pages/preferences/preferences.html, core/templates/dev/head/pages/profile/profile.html, core/templates/dev/head/pages/teach/teach.html, core/templates/dev/head/pages/thanks/thanks.html
this is the partial work on #2099
=> Remove more js files from base.html

core/templates/dev/head/pages/base.html, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/library/library.html, core/templates/dev/head/pages/preferences/preferences.html
=> Fix #2099: remove imageUploader and searchService directive from base.html

core/domain/param_domain.py
=> Fix: add docstrings for core.domain.param_domain.py

core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/ScrollSyncService.js, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/SidebarHighlightingService.js, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/SimpleEditorSidebarDirective.js, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/sidebarHighlightingService.js, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/simple_editor_sidebar_directive.html
SidebarHighlightingService created ! . It has two functions which will change the required sidebar element to error mode and vice versa .
=> Fix #3015 : In the simple editor, add the ability to highlight unfinished questions.

extensions/interactions/GraphInput/GraphInput.html, extensions/interactions/GraphInput/GraphInput.js
* Adds Helper function setMode0
* Updates onClickGraphSVG function
=> Fix #3027 Updates Add Vertex functionality in GraphInput, when vertex is added mode is changed to "MOVE".

.travis.yml, core/templates/dev/head/pages/exploration_editor/EditorModeServiceSpec.js
* Fix #3018: Unit tests for EditorModeService
=> Fix #3018: unit tests for EditorModeService.js

core/templates/dev/head/pages/exploration_editor/ExplorationSaveService.js, core/templates/dev/head/pages/exploration_editor/exploration_save_and_publish_buttons_directive.html, core/tests/protractor_utils/editor.js
changed the default with $modal instance.
=> Fix #3063: change the default confirmation box in "discard draft" to modal

.travis.yml, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/ScrollSyncService.js, core/templates/dev/head/pages/exploration_editor/simple_editor_tab/SimpleEditorSidebarDirective.js
Fix #3011: Adds Smooth Scrolling
=> Fix #3011: Adds Smooth Scrolling

core/templates/dev/head/domain/exploration/QuestionListObjectFactorySpec.js
*Fix #3018: Unit test question list object factory
=> Fix #3018: Unit test question list object factory

PULL_REQUEST_TEMPLATE.md
Update description of PR template.
=> Add note about mentioning bugnum in PR description

core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css
Changed the `height` of the white part as well as the `line-height`.
=> Fix #3066: fixed summary tiles to show the full objective.

core/templates/dev/head/pages/about/about.html
IMPORTANT NOTE (please read, then delete):
The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: introduce the first version of the collection editor.".
=> Fixes #3136 alignment of oppia meaning text in about page after doing required changes

core/templates/dev/head/pages/header_js_libs.html, core/tests/karma-constants.js
Copy of PR https://github.com/oppia/oppia/pull/3177 against release-2.4.1
=> Fix constants XHR in IE9 and IE10 [Release 2.4.1]

extensions/objects/templates/ImageWithRegionsEditor.js, extensions/objects/templates/image_with_regions_editor.html
Fixes https://github.com/oppia/oppia/issues/3051. Image regions can now be resized in any direction by clicking and dragging inside the region in appropriate direction.
=> Fixes #3051: Image regions can be resized by clicking and dragging

core/templates/dev/head/pages/exploration_editor/editor_tab/StateResponses.js, extensions/interactions/TextInput/TextInput.html
=>  Fix: #3169, Fixed the alignment of the submit button in teachOppiaModal

core/templates/dev/head/domain/exploration/AnswerGroupObjectFactory.js, core/templates/dev/head/domain/exploration/ExplorationObjectFactory.js, core/templates/dev/head/domain/exploration/FallbackObjectFactory.js, core/templates/dev/head/domain/exploration/InteractionObjectFactory.js, core/templates/dev/head/domain/exploration/StateObjectFactory.js, core/templates/dev/head/domain/exploration/StatesObjectFactory.js, core/templates/dev/head/pages/exploration_editor/EditorServices.js, core/templates/dev/head/pages/exploration_editor/ExplorationSaveService.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateEditor.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateEditorSpec.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateInteractionSpec.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateResponses.js, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_editor/feedback_tab/FeedbackTab.js, core/templates/dev/head/pages/exploration_editor/history_tab/HistoryServices.js, core/templates/dev/head/pages/exploration_editor/history_tab/HistoryServicesSpec.js, core/templates/dev/head/pages/exploration_editor/statistics_tab/StatisticsTab.js, core/templates/dev/head/pages/exploration_player/AnswerClassificationServiceSpec.js, core/templates/dev/head/pages/exploration_player/PlayerServices.js, core/templates/dev/head/pages/exploration_player/exploration_player.html
=> Fix part of #2863: Create front-end fallback domain object

core/controllers/base_test.py
(Actually, I'm not sure if this is the right way to go about the test).
=> Add a test for home page redirection

core/templates/dev/head/pages/exploration_editor/editor_tab/StateEditor.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateResponses.js
=> Fix #3180: Fixing issues with the teachOppiaModal.

core/templates/dev/head/pages/exploration_editor/feedback_tab/feedback_tab.html, core/templates/dev/head/pages/exploration_editor/feedback_tab/thread_table_directive.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/exploration_player/learner_local_nav.html, core/tests/protractor.conf.js, core/tests/protractor/suggestions.js, core/tests/protractor_utils/editor.js, core/tests/protractor_utils/player.js
=> Fix #1450 Add e2e tests for suggestion acceptance on explorations

core/tests/protractor_utils/player.js
=> Fix naming error in PR 3202.

core/tests/protractor/staticPagesTour.js, core/tests/protractor_utils/editor.js
Also, attempts to resolve a part of #3159
=> Add e2e test to visit the links in the about dropdown

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/footer.html
=> Fixes: footer padding on mobile, #3121

core/templates/dev/head/components/fallback_editor_directive.html, core/templates/dev/head/domain/exploration/FallbackObjectFactory.js, core/templates/dev/head/domain/exploration/TriggerObjectFactory.js, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/exploration_editor/editor_tab/StateFallbacks.js, core/templates/dev/head/pages/exploration_editor/editor_tab/state_editor_fallbacks.html, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_player/PlayerServices.js, core/templates/dev/head/pages/exploration_player/exploration_player.html
=> Fix part of #2863: Create trigger object

core/templates/dev/head/components/summary_tile/CollectionSummaryTileDirective.js, core/templates/dev/head/filters.js, core/templates/dev/head/pages/exploration_player/ConversationSkinDirective.js, core/templates/dev/head/pages/exploration_player/conversation_skin_directive.html
This is based on user test feedback. /cc @rachelwchen 
Note: this needs to go in the upcoming hotfix. /cc @wxyxinyu
=> Only show 'return to collection' when there are no other recommendations to show, so that the learner is not confused about what to do next.

core/templates/dev/head/domain/exploration/ExplorationObjectFactory.js, core/templates/dev/head/domain/exploration/InteractionObjectFactory.js, core/templates/dev/head/domain/exploration/ParamChangeObjectFactory.js, core/templates/dev/head/domain/exploration/ParamChangesObjectFactory.js, core/templates/dev/head/domain/exploration/StateObjectFactory.js, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/exploration_editor/EditorServices.js, core/templates/dev/head/pages/exploration_editor/ExplorationEditor.js, core/templates/dev/head/pages/exploration_editor/ParamChangesEditorDirective.js, core/templates/dev/head/pages/exploration_editor/ParameterMetadataService.js, core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_editor/history_tab/HistoryServicesSpec.js, core/templates/dev/head/pages/exploration_editor/param_changes_editor_directive.html, core/templates/dev/head/pages/exploration_editor/preview_tab/PreviewTab.js, core/templates/dev/head/pages/exploration_editor/preview_tab/preview_set_parameters_modal_directive.html, core/templates/dev/head/pages/exploration_player/PlayerServices.js, core/templates/dev/head/pages/exploration_player/exploration_player.html
Fix part of #2863 .
Decided to do ParamChange object instead of ParamChanges. Sorry for the misnomer in the branch name.
Not sure if ParamChangesObjectFactory should be kept or not.
=> Fix part of #2863: Create ParamChange object factory

core/templates/dev/head/pages/exploration_editor/editor_tab/StateEditor.js
=> Fix #3331: Add OutcomeObjectFactory dependency to teachOppiaModal controller

core/controllers/dashboard_test.py
IMPORTANT NOTES (please read, then delete):
* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: introduce the first version of the collection editor.".
* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables Github to link the PR to the corresponding bug.
=> Fix#2160 Introduce first version of tests involving deleting explorations for creator dashboard

core/templates/dev/head/pages/exploration_editor/EditorServices.js, core/templates/dev/head/pages/exploration_editor/EditorServicesSpec.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateEditor.js, core/templates/dev/head/pages/exploration_editor/editor_tab/StateResponses.js
=> Fix #3283: fix the interactionRulesService error in trainUnresolvedAnswerModal.

core/templates/dev/head/pages/collection_player/collection_player.html
Fixes open-in-new-tab bug in the collection learner view for Firefox.
=> Fix #3062: Right-clicking to open-in-new-tab in collection learner view

core/templates/dev/head/pages/collection_player/collection_player.html
=> Fixed #3327 Changed text from 'highlight' to 'hover over'

extensions/objects/templates/FilepathEditor.js
Add clear error message when an unsupported image format is uploaded.
=> Add error message for unsupported image formats.

core/domain/rights_manager.py, core/domain/rights_manager_test.py
=> Allow admins to edit private activities

app.yaml, core/templates/dev/head/components/background/BackgroundBannerDirective.js, core/templates/dev/head/components/background/background_banner_directive.html, core/templates/dev/head/domain/utilities/UrlInterpolationService.js, core/templates/dev/head/domain/utilities/UrlInterpolationServiceSpec.js, core/templates/dev/head/pages/admin/admin.html, core/templates/dev/head/pages/base.html
Example for referencing directives directly by their URL address.
=> Example for #2700: Background directive directly referenced

core/templates/dev/head/pages/exploration_player/conversation_skin_embed_directive.html, core/templates/dev/head/pages/exploration_player/tutor_card_directive.html
IMPORTANT NOTES (please read, then delete):
* The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: introduce the first version of the collection editor.".
* Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables Github to link the PR to the corresponding bug.
=> Fix #3328 : Change the triangle icon when a user clicks on it

assets/i18n/en.json, assets/i18n/hi.json, assets/i18n/qqq.json, core/templates/dev/head/components/top_navigation_bar/top_navigation_bar_directive.html
#3372:
Added hindi translation for 'Sign In with Google'
=> Fix #3372: Hindi Language Translation for 'Sign In with Google'

.pylintrc, core/controllers/base_test.py, core/domain/exp_jobs_one_off_test.py, core/domain/exp_services_test.py, core/domain/feedback_domain_test.py, core/domain/value_generators_domain.py, core/platform/search/gae_search_services.py, core/storage/base_model/gae_models.py, core/storage/collection/gae_models.py, core/storage/exploration/gae_models.py, extensions/interactions/base.py, main.py, scripts/install_third_party.sh, scripts/pre_commit_linter.py
This should fix the `ImportError: No module named backports.functools_lru_cache` issue.
=> Upgrade pylint-1.7.1 and ensure __init__.py file is present.

core/templates/dev/head/app.js, core/templates/dev/head/appSpec.js, core/templates/dev/head/domain/summary/ExplorationSummaryBackendApiService.js, core/templates/dev/head/pages/collection_editor/editor_tab/CollectionNodeCreatorDirective.js
@souravbadami @kevinlee12 PTAL
=> Fix #2994: fix bug with alert message showing up in collection editor when invalid exploration IDs are entered.

core/domain/user_jobs_one_off.py, core/domain/user_jobs_one_off_test.py, core/jobs_registry.py, core/storage/statistics/gae_models.py
The MR job to store the username distribution has been implemented. This is my first time implementing an MR job :)
=> Fix #3296: MR job to get the distribution of username lengths.

core/templates/dev/head/pages/exploration_editor/editor_tab/state_editor_interaction.html
=> Fix #3342: Add a "Cancel" button to the "Add Interaction / End Exploration" window.

core/templates/dev/head/pages/collection_editor/CollectionEditorNavbarBreadcrumbDirective.js, core/templates/dev/head/pages/collection_editor/CollectionEditorNavbarDirective.js, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/collection_editor/collection_editor_navbar_breadcrumb_directive.html, core/templates/dev/head/pages/collection_editor/collection_editor_navbar_directive.html, core/templates/dev/head/pages/collection_editor/collection_editor_pre_publish_modal_directive.html, core/templates/dev/head/pages/collection_editor/collection_editor_save_modal_directive.html, core/templates/dev/head/pages/collection_editor/editor_tab/CollectionEditorTabDirective.js, core/templates/dev/head/pages/collection_editor/editor_tab/CollectionNodeCreatorDirective.js, core/templates/dev/head/pages/collection_editor/editor_tab/CollectionNodeEditorDirective.js, core/templates/dev/head/pages/collection_editor/editor_tab/CollectionSkillListDirective.js, core/templates/dev/head/pages/collection_editor/editor_tab/collection_editor_tab_directive.html, core/templates/dev/head/pages/collection_editor/editor_tab/collection_node_creator_directive.html, core/templates/dev/head/pages/collection_editor/editor_tab/collection_node_editor_directive.html, core/templates/dev/head/pages/collection_editor/editor_tab/collection_skill_list_directive.html, core/templates/dev/head/pages/collection_editor/history_tab/CollectionHistoryTabDirective.js, core/templates/dev/head/pages/collection_editor/history_tab/collection_history_tab_directive.html, core/templates/dev/head/pages/collection_editor/settings_tab/CollectionDetailsEditorDirective.js, core/templates/dev/head/pages/collection_editor/settings_tab/CollectionPermissionsCardDirective.js, core/templates/dev/head/pages/collection_editor/settings_tab/CollectionSettingsTabDirective.js, core/templates/dev/head/pages/collection_editor/settings_tab/collection_details_editor_directive.html, core/templates/dev/head/pages/collection_editor/settings_tab/collection_permissions_card_directive.html, core/templates/dev/head/pages/collection_editor/settings_tab/collection_settings_tab_directive.html, core/templates/dev/head/pages/collection_editor/statistics_tab/CollectionStatisticsTabDirective.js, core/templates/dev/head/pages/collection_editor/statistics_tab/collection_statistics_tab_directive.html
This is part of PRs to solve #2700.
=> part of Fixes #2700: changes made for all directives included in collection_editor.html

core/templates/dev/head/pages/collection_editor/CollectionEditorNavbarDirective.js, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/collection_editor/statistics_tab/CollectionStatisticsTabDirective.js
PTAL. @tjiang11 @1995YogeshSharma I think there were errors in some of your past PRs.
=> Fix bugs causing the collection editor not to load.

core/templates/dev/head/pages/collection_player/collection_player.html
Fixes #3062 for small screen widths
=> Fix  #3062: Open-in-new-tab for small screen widths in collection learner view 

core/templates/dev/head/pages/moderator/moderator.html
@Arunabh98 -- thanks for spotting this bug! I think this fixes it; PTAL?
=> Add missing dependencies so that the moderator page works again.

core/templates/dev/head/pages/collection_editor/editor_tab/collection_node_creator_directive.html
Fix #3411 for button classes on the collection editor. 
I got 401's trying to access the collection editor on my dev server, but the changes seemed trivial enough.
=> Fix #3411 fix button classes on collection editor

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/Base.js, core/templates/dev/head/pages/base.html, core/tests/protractor.conf.js, core/tests/protractor/accessibility.js
This PR fixes issue #2978 of adding a skip navigation link to the main content in all pages of the website.
=> Fix #2978: Add a skip navigation link

core/controllers/cron.py
Fixes part of issue #4374 . Added doctsrings for core/controllers/cron.py
- These should run automatically, but if not, you can manually trigger them locally using `python scripts/pre_commit_linter.py` and `bash scripts/run_frontend_tests.sh`.
- If you're a new contributor, please ask on [Gitter](https://gitter.im/oppia/oppia-chat) for someone to assign a reviewer.
- If you're not sure who the appropriate reviewer is, please assign to the issue's "owner" -- see the "talk-to" label on the issue.
=> Fixed part of issue #4374 :Added docstring for cron.py

extensions/interactions/FractionInput/directives/fraction_input_interaction_directive.html
This PR fixes #4692 , I've added styling in the HTML so that it doesn't hinder with other elements.
- These should run automatically, but if not, you can manually trigger them locally using `python scripts/pre_commit_linter.py` and `bash scripts/run_frontend_tests.sh`.
- If you're a new contributor, please ask on [Gitter](https://gitter.im/oppia/oppia-chat) for someone to assign a reviewer.
- If you're not sure who the appropriate reviewer is, please assign to the issue's "owner" -- see the "talk-to" label on the issue.
=> Fixed issue #4692: Fixed styling for input text field.

core/templates/dev/head/components/side_navigation_bar/side_navigation_bar_directive.html
Fixes #4746 
- These should run automatically, but if not, you can manually trigger them locally using `python scripts/pre_commit_linter.py` and `bash scripts/run_frontend_tests.sh`.
- If you're a new contributor, please ask on [Gitter](https://gitter.im/oppia/oppia-chat) for someone to assign a reviewer.
- If you're not sure who the appropriate reviewer is, please assign to the issue's "owner" -- see the "talk-to" label on the issue.
=> Fixes issue #4746 : Sidebar links not available on desktop view

core/templates/dev/head/pages/exploration_editor/editor_navigation_directive.html
=> Fixes #3982 : Added 'open' in the open feedback thread summary.

core/templates/dev/head/components/summary_tile/CollectionSummaryTileDirective.js, core/templates/dev/head/components/summary_tile/ExplorationSummaryTileDirective.js, core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/domain/learner_dashboard/LearnerDashboardIconsDirective.js, core/templates/dev/head/domain/learner_dashboard/LearnerPlaylistService.js, core/templates/dev/head/domain/learner_dashboard/learner_dashboard_icons_directive.html, core/templates/dev/head/pages/library/Library.js, core/templates/dev/head/pages/library/library.html
Fixes issue #4323 
In this issue, I fetch the activities created by the user and then negate it with the total activities present. The resulting will have option for "Add to playlist" present on thier respective tiles.
=> Fixes #4323: Fixed creator's option to add to playlist

core/templates/dev/head/pages/topic_viewer/topic_viewer.html
This PR fixes URL for Topic viewer page. The page was breaking after the merge.
=> URL fix for topic viewer page
