oppia/oppia

core/templates/dev/head/css/oppia.css
=> Fix CSS bug: align tick marks in gallery dropdowns with the corresponding rows

core/templates/dev/head/forms/formBuilder.js, core/templates/dev/head/forms/formBuilderSpec.js
Changed core/templates/dev/head/forms/formBuilder.js to allow entry of expressions of .2 and ,2 etc. Also added functionality for using % signs. Related to issue #919.
=> #919 Changes to formBuilder.js

core/templates/dev/head/components/exploration_creation_button.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/ExplorationEditor.js, core/templates/dev/head/editor/exploration_editor.html, core/templates/dev/head/editor/state_editor_content.html
Implementing improvements (mostly suggested by @tngoon):
* Change placeholder for 'goal' in the exploration creation modal
* Make editor sidebar a bit wider (and taller)
* Change placeholder text for initial card
* Change tutorial text for content section
* Make the number of changes next to "save changes" less prominent.
=> Wording and UI improvements, per Tricia's suggestions.

core/templates/dev/head/editor/ExplorationEditor.js
@BenHenning Instead of disabling the save button i have to check the state of the modal. if open then prevent another modal from opening.
Thanks a  lot for the first feedback.
=> Fixes #762

extensions/skins/conversation_v1/Conversation.js, extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
When progress dots are too many then I had to slice the array and show only certain range but the range keeps updating based on where  the current dot is. 
I changed from using ```$index``` to ```id```  because when using  ```$index```  its hard to keep track of sliced dots Eg. if sliced portion is from 6-10 but 6 will be at index zero and current page will be 0 instead of 6.
But i have made ```id``` start from zero too like ```$index``` so that it does not break any thing. 
I have chosen 25 to be maximum number of Dots  shown before they start to scroll horizontally underneath arrows @seanlip what do you think?.
=> Made progress dots scroll horizontally underneath left and right arrows when they are too many

core/templates/dev/head/app.js, core/templates/dev/head/components/answerGroupEditor.js, core/templates/dev/head/components/answer_group_editor.html, core/templates/dev/head/css/oppia.css
+ Made sure the input name consists of alphanumeric characters, spaces and/or hyphens ONLY
+ disable submit button when the form has error
+ display help message/error message instantly when you include invalid character
+ change border of input from blue (on focus) to red to show error in the input
=> stateName client-side validation  Fixes #950

.travis.yml
Updated the Travis CI configuration to send email notifications to Sean and Ben when a build succeeds or breaks after a commit. In particular, email notifications will only be sent when a build changes (goes from succeeding to failing or vice versa). Also, this overrides the default behavior of notifications wherein the committer will no longer receive an email if their commit breaks (though I'm not sure they did before, either). See for more information:
http://docs.travis-ci.com/user/notifications/#Email-notifications
=> Updated the Travis CI configuration to send email notifications

core/domain/dependency_registry_test.py, core/domain/interaction_registry_test.py, extensions/dependencies/dependencies_config.py, extensions/dependencies/jsrepl.html, extensions/dependencies/skulpt.html, extensions/interactions/CodeRepl/CodeRepl.js, extensions/interactions/CodeRepl/CodeRepl.py, scripts/install_third_party.sh, scripts/setup.sh
Fixes #986.
Replaced the JSRepl dependency with Skulp, updating the CodeRepl interaction in the process. This commit removes the functionality to evaluate JavaScript, CoffeeScript, and Ruby in the CodeRepl interaction. It now only supports Python 2.7 (though there is experimental support in Skulpt for Python 3.x).
=> Replaced the JSRepl dependency with Skulpt.

core/templates/dev/head/app.js, extensions/skins/conversation_v1/Conversation.js
I've tested this on both IOS 8 and Android 5.1.1.  Another option would be to check the device against a long list of known mobile devices though that approach may be more trouble to maintain.
Are there any particular places besides text input that the mobile autofocus should be reworked?
=> Adds service to check if the user is on mobile device. Fixes #1006

core/templates/dev/head/components/visualizations.html, core/templates/dev/head/components/visualizations.js, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/EditorServices.js, core/templates/dev/head/editor/exploration_graph.html, extensions/interactions/Continue/validator.js, extensions/interactions/baseValidator.js, extensions/interactions/baseValidatorSpec.js
I had two options to show marker either inside the  or outside the node *(see pictures below)*
I guess @amitdeutsch  will have a suggestion on which is the best way to show.
And Also @amitdeutsch should we use tooltip or just title to show list of errors?
Any suggestions?!
Thanks
=> Displaying warning markers in the exploration graph  Fixes #696

extensions/interactions/MusicNotesInput/MusicNotesInput.js, extensions/interactions/MusicNotesInput/MusicNotesInputSpec.js, extensions/interactions/MusicNotesInput/static/css/musicNotesInput.css
fixes #987 and #989. 
Music widget doesn't load squished now. Waits for page to load before getting the dimensions of the parent div (card). Now the widget will always display properly for the size of the page it has been initially loaded for. 
There is still an issue that needs to be tackled seperately. Two cases: 
1. When the page is first loaded in the full two card style, the widget will look fine and all the sizes will be consistent. From there if the user resizes the page down to the one card style, the widget is still hidden and thus its height is incorrect when recalculating after the reisze event (I used the visibility property hidden instead of display:none and that seems to help, but there are still some problems with drastic resizing).
2. When the page is first loaded in the …
=> Music widget waits for page to load before displaying.

extensions/rich_text_components/Link/Link.html
/cc @brokenairplane 
Note: this turned out to be surprisingly tricky. The whitespace was due to whitespace in the HTML. I'm not sure if this is the best solution; @amitdeutsch WDYT?
=> Remove whitespace around links in RTEs.

core/domain/exp_jobs_one_off.py, core/domain/rights_manager.py, core/storage/collection/gae_models.py, core/storage/exploration/gae_models.py
@kerryxwang -- would you mind taking a look at this? I did a bit of standardizing on the first_published_msec time and some stuff related to whitespace.
Also, I made one change: I asked callers to check that first_published_msec is not set before setting it. This is because the job really should just overwrite the time, without checking anything, because it's computing it from scratch. However, the incremental update does need to do the check, so it seems to me that it's better to have a standalone method that just replaces the msec value and leave validation to the caller. What do you think?
=> Minor tidying up of first-published job code.

app.yaml, appengine_config.py, core/tests/gae_suite.py, scripts/install_third_party.py, scripts/install_third_party.sh, scripts/run_backend_tests.sh
I think I finally got this working!
@isaac-friedman, @michaelWagner, @jacobdavis11, @BenHenning, @stephenchiang -- can you please check this on your machines and see if it works? Basically:
1. Follow the instructions in the 'Prerequisites' section in the installation instructions for your local machine ([Linux](https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Linux%29#prerequisites), [Mac OS](https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Mac-OS%29#prerequisites)).
2. Run
```
bash scripts/run_backend_tests.sh --test_target=core.domain.classifier_services_test.py
```
If all tests pass -- it works! If not, I'd be grateful if you could send me any console errors you run into.
=> Install numpy using pip.

core/templates/dev/head/components/visualizations.html, core/templates/dev/head/editor/exploration_editor.html
prevent window juddering on hover over navbar feedback link. @seanlip  can you also produce this? hover over navbar feedback icon, then juddering occurs before tooltip is displayed.
=> Added title of states bak which display on hover Fix #1167

extensions/skins/conversation_v1/player.html, extensions/skins/conversation_v1/static/conversation.css
@seanlip would you mind taking a look at this? This makes the supplement card width be dynamic based on the screen width. Note that this affects all supplements, though I believe the only other one we use is Image Region select; this would cause the image size to change dynamically, which may or may not be a problem. Thanks!
=> Changed supplement width to be dynamic.

.travis.yml
(This commit should be considered a test, until Travis checks pass. If they do, this fixes #1207.)
=> Speed up Travis checks by making backend coverage reporting non-blocking.

core/templates/dev/head/components/exploration_summary_tile.html, core/templates/dev/head/css/oppia.css
@seanlip this solution feels a bit specific to the current size of the gallery tiles, but I couldn't figure out a more general solution. At least this removes the text-align: center issue. Fixes #1217.
=> Centered the gallery tiles container

extensions/interactions/MultipleChoiceInput/MultipleChoiceInput.js, extensions/interactions/MultipleChoiceInput/MultipleChoiceInputRulesServiceSpec.js, extensions/interactions/MultipleChoiceInput/MultipleChoiceInputRulesSpec.js
I've left the backend rules for now, since they are used by some backend tests. They will be deprecated when we remove the backend tests' dependence on rules.
=> Add frontend rules for multiple choice input

extensions/skins/conversation_v1/Conversation.js
By animating for the first card, front-end error occurs for a Supplemental Interactive.
=> Don't animate for the first card

gulpfile.js, scripts/run_e2e_tests.sh
I had to run a gulp build task in the ```scripts/run_e2e_test.sh``` so as if you did not run ```bash scripts/start.sh``` at first you wont face the issue of missing minified css and js.
=> Run a build task when running intergration test Fix #1272

core/tests/karma.conf.js, scripts/run_frontend_tests.sh
So actually karma.conf.js receives args in array format in the form of 
```
[ 'node', 'command', 'path_to_karma.conf', ' <options>']
```
So it was unreasonable to add arg like ```minify=True``` as it will be treated as  a single string. And I was torn between checking  ```minify``` argument by  looping all arguments( ended using this) and by checking just the forth argument ```process.argv[3]``` to see if is equal to minify.
And it looks like build with minification takes sometimes.
=> Modified to run test in both production and development Fixes #1275

core/templates/dev/head/profile/profile.html
This issue is committed to the user-profile branch.
This changes the "Statistics" tab text to "Impact".
=> Issue #1247 Change "statistics" to "Impact"

core/templates/dev/head/player/conversation_skin_directive.html, extensions/interactions/CodeRepl/CodeRepl.html, extensions/interactions/CodeRepl/CodeRepl.js
Initial stab at #1308 and #1309. This will probably need to be redesigned (or added to) later, but not being able to see the output/error is a critical issue, so I'd like to push a fix for it.
/cc @amitdeutsch , @cjerry
=> Show output and error messages for coderepl interaction.

core/templates/dev/head/css/oppia.css
This little CSS tweak fixes #1279 by overwriting bootstrap's default tooltip max-width to none.
=> Overwritten bootstrap default tooltip width. Fixes #1279

core/templates/dev/head/editor/ExplorationEditor.js
Changed placement of a popover for intro tutorial.
=> UI fix in intro tutorial #1286

extensions/interactions/CodeRepl/CodeRepl.js
This is to fix issue with importing builtin python modules, which are supported by skultp.
=> Add support for import of builtin python module in skulpt (fix-#1383)

core/templates/dev/head/admin/admin.html
Admin page couldn't inject some constants, i.e PARAMETER_TYPES
=> Fix frontend error in admin page

core/templates/dev/head/app.js, core/templates/dev/head/appSpec.js
We used date.toLocaleDateString() function which formatting conventions depends from locales. This caused test fails in my environment.
=> Normalize format of getLocaleDateString function return

core/templates/dev/head/appSpec.js, core/tests/protractor/richTextComponents.js
Two test were failing:
*  core/tests/protractor/richTextComponents.js has a list of console logs to be ignored. These are external logs from google-cast-sdk. I just added a new error that was not listed before.
* core/templates/dev/head/appSpec.js was missing a date format used in Latin America, dd/mm/YY.
=> Ignoring external console error. Adding latin american date format.

core/templates/dev/head/components/outcome_editor_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/state_editor_content.html, core/templates/dev/head/services/explorationContextService.js, extensions/rich_text_components/Image/Image.html, extensions/rich_text_components/Link/Link.html, extensions/rich_text_components/Link/Link.js, extensions/rich_text_components/Video/Video.html, extensions/rich_text_components/Video/Video.js
This patch fixes following,
1. It uses a sibling div to editor div for overlaying it with a gray mask. Thus no need for individual elemental gray masking when editor is being hovered in editor mode. In turn it also prevents opening of links and playing of videos in editor when it is clicked.
2. It prevents focus on links and videos while tabbing on editor screen. But focus via tabbing will be available while in preview mode  or learner mode.
=> Add gray overlay on editor when it is hovered.

core/domain/collection_services.py, core/domain/collection_services_test.py
This PR provides a check against the addition of non-existent exploration into a collection.
=> Check for non-existent exploration within a collection 

scripts/release_info.py
Turns out that adding that second " introduced a bug that a `"` appears after the commit message.
=> Fixed appearance of " in commit titles of release_info script output

core/templates/dev/head/header_js_libs.html, manifest.json, scripts/install_third_party.py
MathJax version updated to 2.6.0.
Fixes #1421 - verified that black bar no longer appears on card or in preview with Chrome 48.0.2564.97 and Firefox 43.0.4 .
=> Update MathJax to v2.6.0. Fixes #1421.

gulpfile.js, scripts/install_third_party.sh
As gulp-minify-css is [deprecated](https://www.npmjs.com/package/gulp-minify-css#deprecation-warning)  , Is changed in favour of gulp-cssnano
=> replaced deprecated gulp-minify-css in favour of gulp-cssnano

core/templates/dev/head/base.js, core/templates/dev/head/directives.js, extensions/rich_text_components/VideoMp4/VideoMp4.js
We now clear the src= tag after a video leaves the user's view to release memory and browser resources.
Originally escalated this as a bug in Chrome. Upon review learned it's each site's responsibility to embed video resources according to W3C spec 4.7.10.18.  Ref: https://www.w3.org/TR/html5/embedded-content-0.html
I confirmed this fix appears to function as expected locally (wasn't able to reproduce the prior bug), but wasn't sure how to manually re-execute the video element's load() method after clearing the src= tag as suggested in the W3C spec above. The Chrome team suggested clearing src='' may be sufficient, but if anyone in review is familiar with how best to re-execute the element's load() method it would bring us fully in alignment with the spec.
=> Bugfix for mp4 video playback

.gitignore, Vagrantfile, scripts/install_prerequisites.sh
Builds a Vagrant machine with all dependencies so that it can build and run Oppia. Useful for users on Windows, users who want to test against a clean environment, to ensure a clean environment without polluting the host machine, or for people who are otherwise having issues building Oppia on their host (like yours truly). 
Also adds a VAGRANT env variable set to `true` for use by any scripts that may need to behave differently if inside a vagrant machine. 
Finally, Vagrant creates a `.vagrant` directory with information about the VM state, so I have added that directory to `.gitignore`.
=> Improve Vagrantfile for development environment

core/templates/dev/head/components/AnswerGroupEditorDirective.js, core/templates/dev/head/components/OutcomeDestinationEditorDirective.js, core/templates/dev/head/components/OutcomeEditorDirective.js, core/templates/dev/head/components/answer_group_editor_directive.html, core/templates/dev/head/components/outcome_destination_editor_directive.html, core/templates/dev/head/components/outcome_editor_directive.html, core/templates/dev/head/editor/StateResponses.js, core/templates/dev/head/editor/state_editor_responses.html
Hides feedback editor if interaction is linear (Continue) and has no existing feedback.  Modifies information text and tooltip warnings when feedback is not shown.
=> Hide feedback editor for continue interaction

core/templates/dev/head/components/RuleTypeSelectorDirective.js, core/templates/dev/head/components/rule_editor_directive.html
Before, when you select a "rule type", $scope.rule.type in the parent scope changes and invokes "onSelectNewRuleType(newRuleType)". 
I think, one of these is unnecessary and was confusing me. However, I might have wrong argument.
=> Removed unnecessary two way binding

scripts/pre_push_hook.py
Fixes #1488.
The pre_push hook had the issue that he was linting the state of the current active branch and not the actual state of the branch being pushed.
This PR fixes this by trying to change to the branch under test.
=> Pre-push hook now switches to the correct branch before linting.

core/templates/dev/head/css/oppia.css
Fixes the math formula and text overflow in the rule editor select dropdown (issue #1534)
=> fix math formulae overflow - #1534

core/tests/protractor/privileges.js
After fixing issue #1533 , one of the e2e tests failed. Simply changing the url from `/` to `/my_explorations` fixes this.
Thanks for pointing this out, @seanlip . Please review
=> Fix failing e2e test by correcting url

core/templates/dev/head/components/outcome_editor_directive.html, core/templates/dev/head/editor/state_editor_responses.html
I'm not sure if this is an issue, but clicking the edit icons doesn't open up the editor for the exploration responses.
Screenshot for the edit icon - 
So here's the fix :)
=> Allow editing of exploration responses via edit icons

core/templates/dev/head/css/oppia.css
Fixes the overlap of images in the Html-select dropdown that occurs in the rule editor when creating an exploration.
=> fix select dropdown image overlap (#1536)

core/templates/dev/head/forms/formBuilder.js
As opposed to a $watch, which slows down the editor significantly.
Made to address #945.
=> Add event so RTE can be alerted to external htmlContent changes

core/domain/user_jobs_continuous.py, core/domain/user_jobs_continuous_test.py
This is based off of issue #1288 and the design attached there. 
The only piece of this that was tricky to actually fully make work as I would have wanted is definition of reach. As it is defined in the design doc, it uses "the number of users that have given an answer per card", which is really hard to define given what information we have.
The information we have is:
* Number of sessions to hit this state (so multiple playthroughs by the same person would count separately)
* Number of times this state was hit (so multiple times to the same state in the same playthrough would count separately)
* Number of times this state was hit but no answer was given (which is a max of one time per session)
So what I have right now is `first_entry (per session) - no answer given`, which in theory is …
=> Switch to using new impact metric

.travis.yml, scripts/run_e2e_tests.sh, scripts/run_frontend_tests.sh, scripts/run_presubmit_checks.sh, scripts/setup.sh
Updated the frontend test script to not run the second pass of tests by default. It still runs for the presubmit check, but not by default. Also, added an optional flag to skip the installation process. This is useful for when third party dependencies have already been installed. These two flags together significantly speed up running the frontend tests. We may want to consider setting the install dependencies flag on by default and having the frontend checks error-out if third party dependencies haven't been installed yet.
=> Added flags to the frontend test runner script

core/templates/dev/head/pages/privacy.html
This PR to fix a minor bug mentioned in issue [#1613](https://github.com/oppia/oppia/issues/1631)
Just not properly closed `<em>` tag.
=> Fix #1631: text in sidebar of privacy page is italicized

core/templates/dev/head/forms/formBuilder.js, core/templates/dev/head/services/explorationContextService.js, core/templates/dev/head/services/explorationContextServiceSpec.js, manifest.json
This commit are intended to update textAngular to 1.5.0
Rangy is also added in dependencies to solve issues with new version of textAngular, since minified version of rangy provided in textAngular package broke some frontend tests.
Inclusion of rangy as independent dependency solves this issues and everything works as it is expected to.
=> Update textAngular to V 1.5.0

core/templates/dev/head/components/RuleTypeSelectorDirective.js
This PR to fix a major bug mentioned in issue #1662
It was due to removing the data binding in a previous commit 0f400f21c6cc70d44d98f2628929c33ded07b1e6
=> Fixes #1662: Music notes add response dialog does not work

Vagrantfile, scripts/run_frontend_tests.sh, scripts/setup.sh
Install XVFB and adjust setup.sh to prepend `xvfb-run` to frontend test commands if using Vagrant.
=> Fix frontend tests in Vagrant VM

.travis.yml, scripts/setup_gae.sh, scripts/start.sh
Cached a few folders as per #1636, ran them through Travis to see how long build time takes now.
Times go (in minutes): only linting, only front-end testing, only back-end testing, back-end testing and coverage.
- [Build without caching](https://travis-ci.org/mcab/oppia/builds/117892359): 10, 7, 19, 115.
- [Caching ../node_modules](https://travis-ci.org/mcab/oppia/builds/117894736): 9, 6, 14, 120.
- [Caching all four folders](https://travis-ci.org/mcab/oppia/builds/117896812): 8, 3, 12, 115.
Had to resolve Google App Engine already existing in the cache, leading to [Travis not knowing what to do](https://travis-ci.org/mcab/oppia/builds/117896270). Moved making the directory, downloading, and extracting GAE to the proper folder into scripts/setup_gae.sh instead of having installation …
=> Caching files for Travis

core/templates/dev/head/editor/exploration_editor.html
=> In the logged-out version of the editor view, the feedback tab overlaps the sign-in menu. #1679

core/controllers/profile.py, core/controllers/profile_test.py, core/domain/user_services.py, core/domain/user_services_test.py, core/storage/user/gae_models.py, feconf.py
First milestone of #1357 
Changes:
- Modifies UserEmailPreferencesModel
- Modifies user_services.update_email_preferences()
- Modifies user_services.get_email_preferences()
- Add Default value for membership notifications in feconf
- A backend test is also added in user_services_test.py
=> Add preference for membership notifications in UserEmailPreferencesModel and relevant changes

core/domain/exp_services.py, core/domain/exp_services_test.py
FIxes #1723 .
Changed misnamed _get_exploration_summary_dicts_from_models to _get_exploration_summaries_from_models in exp_services
=> [#1723] Fixed Misnamed function in core.domain.exp_services

core/controllers/profile.py, core/templates/dev/head/profile/Preferences.js, core/templates/dev/head/profile/PreferencesSpec.js, core/templates/dev/head/profile/preferences.html, core/tests/protractor/preferences.js
Milestone 2 of #1357 
- Modified preferences.html to add a new checkbox property for editor role email
- Modified Preferences.js to synchronize this new added property with backend
- Modified profile.PreferencesHandler to take new values from frontend and update UserEmailPreferencesModel
- Added a new PreferencesSpec.js test file for frontend tests.
=> Add checkbox for editor role emails receiving agreement on preferences page

core/templates/dev/head/forms/formBuilder.js
Not sure if this is the best place but it seems to fix the issue in my testing.
=> Fix #914: removes RTE icon resize handlebars in Firefox.

extensions/interactions/ItemSelectionInput/ItemSelectionInput.js
Added a simple check for case when zero items are selected in multiple select interaction.
=> Fix #1766 - initialize zero selection for multiple select interaction

core/templates/dev/head/player/conversation_skin_directive.html, extensions/interactions/ItemSelectionInput/ItemSelectionInput.js
When two cards are shown side-by-side in the learner view, the fix changes the css class to the style .instructions-no-button. I added an !important rule to both hover and active. Not sure if this is the "proper" way to handle this case, would love to know if this is the best way to handle this or another css method is preferable.
=> Fix #1814 - Added css rules for wide window buttons

core/templates/dev/head/css/oppia.css, core/templates/dev/head/editor/exploration_history.html
Fix #1829 
A commit with just two files was made that were changed.
Extra white space between username and exploration revision was reduced
=> Fix #1829 Reduce space between username and exploration revision

.jscsrc, core/templates/dev/head/exploration_editor/EditorServices.js, core/templates/dev/head/expressions/typeParser.js, core/templates/dev/head/expressions/typeParserSpec.js, core/templates/dev/head/filters.js, scripts/install_third_party.sh
Updates JSCS to v3.0.3 and fix corresponding the linter errors.
=> Update JSCS to v3.0.3

core/controllers/home.py, core/domain/collection_domain.py, core/domain/collection_domain_test.py, core/domain/collection_services.py, core/domain/collection_services_test.py, core/domain/exp_domain.py, core/storage/collection/gae_models.py, core/storage/exploration/gae_models.py, core/templates/dev/head/domain/collection/CollectionObjectFactory.js, core/templates/dev/head/domain/collection/CollectionUpdateService.js, core/templates/dev/head/domain/collection/CollectionUpdateServiceSpec.js, core/tests/test_utils.py, data/collections/welcome_to_collections.yaml, feconf.py
Introduced a language_code to the collection data structure and updated its schema version to 2, where new collection have a default language code of 'en'. The support for this language code has been implemented end-to-end for collections, including in the collection creation dialog and for search queries (though this commit does not implement collection searching).
=> Fix #1697: upgrade collection schema version to 2 by introducing language codes to collections (where the default is 'en').

core/templates/dev/head/player/ConversationSkinDirective.js, core/templates/dev/head/player/conversation_skin_directive.html
Fix #1813.
The reason was when ng-if element injected into animation it doesn't know sub dom elements.
=> Fix #1813: Fix jerky animation when card expanded to show previous answers

scripts/install_third_party.py
Fix #1848 
If the user is behind a proxy and is installing Oppia on Vagrant there is error generated like the one here at this pastebin --> http://pastebin.com/z34hsmi9
So this PR solves this problem and sets proxy to empty string if the user is on Vagrant
=> Fix #1848 as per suggesstion by @bbriggs for setting up the proxy if the user is on Vagrant

core/tests/protractor_utils/editor.js, core/tests/protractor_utils/general.js
Without this I and Arun get errors that the state graph cannot be clicked on, though Travis doesn't seem to care.
=> Protractor bugfix: Scroll to the top of the page before clicking on the state graph.

core/controllers/base.py
I noticed (while working on the dev server) that if I log in as a new user by clicking the top right button in the splash page, I get taken through the registration flow and end up ... back at the splash page. This seems a bit silly.
So I changed the redirection-on-signup to point to "/" instead (which would redirect to the logged-in homepage) in all cases. Any objections?
@kevinlee12 @BenHenning @jacobdavis11
=> After a user logs in via the top right button, take them to the 'logged in' home page, which is the 'my explorations' page.

core/templates/dev/head/components/exploration_summary_tile_directive.html
=> Fix #1840: Fix oval contributor icons in exploration summary tile 

core/templates/dev/head/player/conversation_skin_directive.html
=> Fix #1815: Place tutor avatar above the supplemental card

core/templates/dev/head/library/Library.js
This fixes #1864 by adding in checkers and jQuery methods to ensure that JS will wait until the current iteration of scroll is completed before allowing the user to click it again. There was a deliberate choice not to queue the action as there would be a perceived lag by the user. Employing start and complete methods in jQuery would guarantee that the action has truly started and completed.
=> Fix #1864: Fix carousel scrolling when user clicks on button quickly 5-7 times

core/templates/dev/head/css/oppia.css
This fixes #1911 with which the overlay shadow did not have the proper height.
=> Fix #1911: Fix carousel scroll overlay height

core/domain/exp_services.py, core/domain/exp_services_test.py, core/domain/summary_services.py, core/domain/summary_services_test.py
Implement part 2 of #1906. This replaces the usage of average ratings when determining the order of top rated categories.
=> Fix #1906: Implement Wilson Score for Top Rated

core/templates/dev/head/exploration_editor/ExplorationEditor.js, core/templates/dev/head/exploration_editor/settings_tab/SettingsTab.js
Fix for #1894. The category dropdown list was creating an empty element at the bottom, which caused the dropdown to scroll down to select the item. The fix changes the way new elements are inserted in the array backing the dropdown list, using unshift (insert at the top) instead of push (append).
=> Fix #1894: Dropdown list creates empty item and scrolls to the bottom.

core/controllers/profile.py, core/templates/dev/head/profile/Profile.js, core/templates/dev/head/profile/profile.html
Added a set of `ng-if` statements to determine whether the profile page belonged to the current user or not; if it did, the profile image hyperlinks to `/preferences`, however if it does not, the profile picture contains no hyperlink.
=> Fix #1793: Set hyperlink to /preferences on profile image contingent on whether the profile page was the current user's or not.

core/templates/dev/head/css/oppia.css
Oops, @souravbadami -- looks like this regressed due to a bad merge. PTAL!
=> Fix #1963: elongate exploration summary tile lengths.

scripts/setup.sh
Return values for success/failure were inverted. 
String equality test failed on cases where in should have passed. 2.7.11 should have passed, but did not.
Update explanatory comments.
=> Fix #1394: Fix test_python_version in setup.sh

core/templates/dev/head/css/oppia.css
After the change it looks like the following:
=> Fix #2000:  Change small screen footer height

core/templates/dev/head/library/Library.js
I think the issue was due to a one-larger value of variable `titleDisplayCount` which resulted in the `oppia-library-carousel` being assigned 416px instead of 208px. Adding 20px to the `titleDisplayWidth` while calculating `titleDisplayCount` fixed the issue.
=> Fix #1979 : Right scroll button of the library carousel is flushed to the right at 514px

core/templates/dev/head/css/oppia.css, core/templates/dev/head/profile/profile.html
The interests listed by an Oppia user weren't wrapping within the column on the profile page.  I fixed the code in profile.html and now it seems to work fine.
=> Fixed issue 2075, interests not wrapping on profile page

core/templates/dev/head/exploration_editor/main_tab/SidebarStateName.js
=> Fix #2078: prevent unsaved changes from being lost when editing a state name.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/footer.html
New css class is added in``` oppia.css ```  in the media query to adjust the left margin on smaller screens to get expected styling
=> Fix #2091 Adjust footer on smaller screens

core/domain/feedback_domain.py, core/domain/feedback_domain_test.py, core/domain/feedback_services.py, core/domain/feedback_services_test.py, core/storage/feedback/gae_models.py, core/storage/feedback/gae_models_test.py
Milestone 3 of feedback message email service
Implements send_feedback_message_email function in feedback_services. Relevant tests have been added to feedback_services_test.
This function is responsible for creating new model or modifying existing model of UnsentFeedbackEmailModel, depending upon whether model already exists or not.
=> Part of #461: implement send_feedback_message_email function in feedback_services

core/tests/performance_framework/perf_domain.py, core/tests/performance_framework/perf_services.py, core/tests/performance_tests/base.py, core/tests/performance_tests/splash_test.py
This is the second PR for #2047, in continuation with #2068. It implements a domain object for containing multiple PageSession objects and returning average metrics.
=> Fix #2047: introduce multiple PageSession object (new).

core/templates/dev/head/profile/Preferences.js, core/templates/dev/head/profile/preferences.html
Added function to force select2 dropdown refresh after its content being translated.
=> Fix #2092: Placeholder sometimes shows 'I18N_PREFERENCES...' on subject interests and preferred languages.

core/tests/gae_suite.py, core/tests/performance_framework/perf_services.py, scripts/install_third_party.sh, scripts/pre_commit_linter.py, scripts/run_performance_tests.sh, scripts/setup.sh
Fix #2154: We were installing xvfb only for vagrant, but we require it for performance tests. So, now installing it outside vagrant also. Installing it for all platform needs to be looked into. And, currently it requires `sudo` to install it, which is a bit obtrusive.
=> Fix #2154: xvfb not found.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/library/Library.js
This PR fixes #2164, the decision to maximize the exploration summary tile was to ensure that the carousel width would fit all 4 collections if present and that the carousel width is consistent for all groups. 
Only explorations:
Mixed:
=> Fix #2164: Expand exploration summary tile width to match collection summary tile width

core/templates/dev/head/player/conversation_skin_directive.html
This seems to be on account of the media screen size css rules, added a css rule for non-terminal, non-narrow, smaller media screen incidents. Note this does throw off the fluidity of the movement between moving between smaller and larger media screen in some cases. Let me know if there is a better way to do this.
=> Fix #2113: Added Wide option for non-terminal, non-narrow cards

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/about.html
Simple fix for the issue  'Improve About pages tabs for iOS #2023'.
As suggested in the discussion, changed the names to shorter version and removed the `flex-wrap` property which was making the tabs to stack up when screen sizes were small.
Tested it with smallest browser width possible, seems fine
=> Fixes #2023

core/templates/dev/head/css/oppia.css, core/templates/dev/head/library/library.html
This PR makes adjustments to the positioning of the View All button so that it is not flushed right on half screens and smaller. The UI was tested on desktop (full to smallest Chrome supports), tablets, and mobile.
=> Fix #1841: Fix view all button flushed right appearance

core/templates/dev/head/admin/Admin.js, core/templates/dev/head/admin/admin.html
Fixes #2197 and #2195: Refresh admin page keeps it at the same location; Auto-scroll for viewing output in jobs tab in admin panel.
=> Fixes #2197 and #2195: Refresh admin page keeps it at same location; Add auto-scroll to show output in jobs tab.

core/templates/dev/head/exploration_editor/main_tab/sidebar_state_name.html
As per the suggestions by @seanlip and @KatFrog the Card title ```Done``` button displays ``` Save ``` text and is colored ```Green```
=> Fix #2094 Change Done button to Save button and color it green

scripts/release_info.py
Only write feconf version changes in the release summary output if a change occurred.
=> #2232 Do not show unnecessary feconf version change info in the release info

README.md
Updated the image on ReadMe to the latest image of oppia library. This fixes #2228 and uses #2247 for image.
=> Fix #2228 Updated ReadMe image

core/templates/dev/head/admin/admin.html
Change ul structure to table and add striped rows in order to distinguish each Start new job button easily
=> Fix #2196: alternating colors of jobs list on admin page

core/controllers/base_test.py
=> Fix #2229: test that en.json and qqq.json contain exactly the same keys.

core/controllers/feedback.py, core/controllers/feedback_test.py, core/domain/email_manager.py, core/domain/feedback_services.py, core/templates/dev/head/exploration_editor/feedback_tab/FeedbackTab.js, core/templates/dev/head/exploration_editor/feedback_tab/ThreadDataService.js, feconf.py, main.py
When feedback is already seen, feedback message email should not be sent. This commit takes care of that by removing corresponding feedback message references from UnsentFeedbackEmailModel instance so that they are not present in the sent email.
=> fix #2258: feedback messages should not be sent if user has already seen to them.

app.yaml, core/tests/test_utils.py, feconf.py, main.py, main_taskqueue.py
The aim of this PR is to secure the taskqueue handlers per the guidance at the bottom of [this page](https://cloud.google.com/appengine/docs/python/taskqueue/push/creating-handlers#securing_task_handler_urls).
=> Add a new main_taskqueue.py file for taskqueue handlers.

core/templates/dev/head/css/oppia.css
With some changes in oppia.css I have been able to match the width of the 2 entities while keeping as much of the earlier layout.
=> Fix #2222: width of tiles is adding up to the width of the top bar

extensions/rich_text_components/Link/Link.html, extensions/rich_text_components/Link/Link.js, extensions/rich_text_components/Link/Link.py, extensions/rich_text_components/Link/protractor.js
Since users wouldn't want open a link on the same window as the currently played exploration, the option "Open in same window" is not necessary. My commit removes it from the modal that displays when creator clicks on Link option, on toolbar of a card editor.
=> Fix #1966: remove the option Open in same window in editor

core/templates/dev/head/forms/formBuilder.js, extensions/interactions/ItemSelectionInput/ItemSelectionInput.py, extensions/interactions/MultipleChoiceInput/MultipleChoiceInput.py, schema_utils_test.py
This PR addresses issue #1862. The creator no longer has to remove pre-existing text. The text is replaced by a placeholder which gets removed when the user starts typing.
=> Fix #1862: Creator no longer has to remove pre-existing text in RTEs

core/templates/dev/head/i18n.js
In order to get the currentLanguageCode use
$translate.proposedLanguage() alongside $transalte.use()
Fixes https://github.com/oppia/oppia/issues/2274
currentLanguageCode was set to undefined because the language file could not be loaded within the timeout, hence we got an empty blank field.
=> Fix #2274: I18n.js: Use $translate.proposedLanguage to  eliminate blank field.

core/domain/exp_jobs_one_off.py, core/jobs_registry.py
=> Add diagnostic one-off job to highlight ItemSelectionInput interactions whose answer groups need to be fixed.

core/templates/dev/head/components/activity_tiles_infinity_grid_directive.html
This is a partial fix for #1799. The explorations are centered for a non-mobile device.
=> Fix #1799: The explorations are now centered for a non-mobile device

core/controllers/resources.py
Added cache headers to images served via ImageHandler and set cache duration to 600secs.
/cc @BenHenning @maitbayev PTAL!
=> Cache images served via ImageHandler

core/templates/dev/head/collection_editor/editor_tab/CollectionLinearizerService.js, core/templates/dev/head/collection_editor/editor_tab/CollectionLinearizerServiceSpec.js
Fix #1998: implement tests for collection linearizer service.
Replaces #2153
=> Test collection linearizer service

core/templates/dev/head/css/oppia.css, core/templates/dev/head/player/conversation_skin_directive.html
Addresses: #2311 
Breaks words that are too long onto separate lines in exploration cards, so that they do not overflow the width of the card.
=> Fix #2311: Add word-wrap for exploration card content

extensions/gadgets/base_test.py, extensions/interactions/base_test.py
Fix #2383: tests to check whether interaction template includes js script they require.
/cc @BenHenning @maitbayev
=> Fix #2383: tests to check whether interaction template includes js script they require.

core/controllers/feedback.py, core/controllers/feedback_test.py, core/domain/email_manager.py, core/domain/email_manager_test.py, core/domain/feedback_services.py, core/domain/feedback_services_test.py, core/domain/user_services.py, feconf.py, main_taskqueue.py
Till now Oppia was sending feedback message email to owners of exploration
only. This commit will enable Oppia to be able to send emails to other
participants (other than owners) of thread as well.
For implementation details refer to this [design](https://docs.google.com/document/d/1r0IfWD6AiaeBPUOe-mZnihPMPO0a4Z9Hj_5ImWBeUcg/edit) doc.
=> Fix #2349: Add service for sending feedback email to thread participants.

core/templates/dev/head/player/conversation_skin_directive.html
.. div['.conversation-skin-inline-interaction'] and simplify some logic.
We have a lot of $scope variables in conversation_skin_directive.html,
as well as we have some if-checks inside the template which involves a lot
of variables. It is very easy to get confused when variables tightly
depend on each other.
So the aim of this PR to extract out logics of supplemental interaction
from inline interaction. By doing this will be easier mentally understand the part, and will help upcoming refactoring.
=> Extract non-inline interaction code from

core/templates/dev/head/css/oppia.css
Fixes #2400: increases distance between oppia-page-card and footer, gives oppia-page-card a box shadow (e.g. on various of the 'about' pages and on the 'donate' page), and increases distance between the text on the 'donate' page and the end of the page-card.
=> Fix #2400: 'donations' and 'about' pages cosmetic changes - margins and box-shadow

core/templates/dev/head/collection_editor/settings_tab/CollectionDetailsEditorDirective.js
~~Note: There were some arithmetic errors during frontend testing, so I'm opening a PR to do a Travis test to check if it is replicate-able. **Please do not merge yet.**~~
It is okay to review now, the error above is local. 
Note to reviewer: The alert service was constantly adding errors to the warnings list (disregarding that it already sent an error). Because we will be doing a final check prior to publishing like we do in the exploration editor, I decided we should remove the `alertService` errors and ask the creator to resolve those issues until the very end (which is the same suggestion in the issue comment thread).
=> Fix #2334: Remove title, goal, and category alertService alerts

core/templates/dev/head/player/conversation_skin_directive.html
I couldn't reproduce #2113.
Removing it if possible, otherwise we are introducing one more state of tutor card, which might increase difficulty of understanding the template, already tutor card can be in many states/shapes.
=> Remove conversation-skin-main-tutor-card-wide

core/templates/dev/head/expressions/expressionSyntaxTree.js
Rounded the result of Math.log to 9 decimal places as discussed.
=> Fix errors which occur due to precision error in Math.log

core/controllers/dashboard.py, core/templates/dev/head/css/oppia.css, core/templates/dev/head/dashboard/Dashboard.js, core/templates/dev/head/dashboard/dashboard.html
@seanlip Just one minor thing - the data for collections is obtained through the backend when the creator dashboard is loaded. For each collection, the value of number of nodes it has is absent in this case (in dashboard data), while it's present in the library collection tiles. If it's worth displaying, then I'll go ahead and see how the node_count can also be sent to frontend. wdyt ?
=> Fix #2473: Make collection tiles in dashboard similar as in library.

scripts/backend_tests.py, scripts/run_backend_tests.sh
Add an command line option to enable verbose logging when run backend tests.
=> Fix #2463: Add an argument to show verbose backend log

core/templates/dev/head/dashboard/dashboard.html
The original commit breaks the dashboard view; the contents of the tile spill out of it.
=> Revert "Fix: #2365 : Add right-clickable fix to dashboard tiles (#2481)"

core/domain/feedback_services.py, core/domain/feedback_services_test.py
When a user replies to a feedback thread or changes status of feedback thread, oppia also tries to send email to anonymous users who participated in thread (which raises key/id missing error). This PR fixes that issue and adds back end test to make sure its integrity.
=> Fix: error when sending instant feedback message email to anonymous user

core/templates/dev/head/components/ResponseHeaderDirective.js, core/templates/dev/head/components/response_header_directive.html, core/templates/dev/head/pages/exploration_editor/editor_tab/state_editor_responses.html
Added a way to view multiple rules to a answer group.
Thank you @andromfins for helping with this issue.
=> Fix #2531: show multiple rules for an answer group

core/templates/dev/head/components/forms/FormBuilder.js, core/templates/dev/head/filters.js, core/templates/dev/head/filtersSpec.js
Created an array of whitelisted tags to check for before removing all other tags in pasted content. Tested with Oppia images and tabs and with various styled content from Wikipedia and Stack Overflow.
=> Fix #2025: strip the formatting before pasting in the RTE

core/templates/dev/head/components/forms/FormBuilder.js, core/templates/dev/head/filtersSpec.js, core/templates/dev/head/pages/header_js_libs.html, extensions/objects/templates/ImageWithRegionsEditor.js
Note: This is intended as a hotfix.
/cc @wxyxinyu @BenHenning
=> Fix .load() method breakage due to jQuery upgrade. Also fix error in #2594 arising due to mismatched RTE component HTML representations.

core/domain/config_domain.py
Added config property so that admin can set authorised users who can execute query from query page.
=> Fix part of #2269: Add config property to set authorised query users.

core/templates/dev/head/css/oppia.css
=> Fix #2535: Make 3 column occupy whole width in mobile and small screen devices.

core/templates/dev/head/css/oppia.css
Added `display: inline-block` style to featured-label `span`-tag.
=> Fix #2549: featured-label no more breaks to two lines.

core/templates/dev/head/pages/exploration_player/PlayerServices.js
Problem occured due to some quite nasty side effects regarding updating the "outcome" variable in [PlayerServices.js](https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/pages/exploration_player/PlayerServices.js#L274).
The `classificationResult.outcome` pointed at `oldState.interaction.default_outcome`, so changing the `outcome`-object changed the `oldState`-object and thus the `default_outcome` was changed for the next state.
Fixed this by using `Object.assign()` to clone the `classificationResult.outcome`.
=> Fix #2538: fix fallbacks triggering when they are not supposed to.

Vagrantfile, scripts/setup.sh
Currently, vagrant env is checked for existence of an environment variable that is set at provision time. This does not work all the time when the vagrant system is rebooted.
This fix, adds a file and checks the existence of the file `/etc/is_vagrant_vm` along with environment variable `$VAGRANT` to determine if the host is vagrant and invokes other scripts accordingly.
=> #2637 Determine Vagrant env by checking existence of a file and env var

core/templates/dev/head/css/oppia.css
Created media query to 1100px so as to completely remove overlap between site feedback and exploration cards on library page.
=> Fix #2049: hide site feedback text on smaller devices

core/templates/dev/head/pages/library/library.html
This just copies the collection summary tile to the block used on small screens and uses it for collections.
I have tested it locally and signed the CLA.
=> Fix #2657: Use collection-summary-tile for collections on small screens.

core/templates/dev/head/pages/exploration_player/progress_dots_directive.html
Followed the examples given in #2676, here's a [screenshot](https://pageshot.net/z2DJtov3x8hut2hM/oppia-dev).
=> Fix 2679: Use the correct colors for the progress dots.

core/templates/dev/head/pages/exploration_editor/simple_editor_tab/simple_editor_body_directive.html
This adds texts above the two bottom buttons on the simple editor: "Add new question" & "Finish exploration". These texts are shown right above the button when the button is hovered.
I first tried doing this so the `<span>` description tag was inside the button element in the html, and setting it above the button using `position: relative`. This however broke looked different on different browsers. Decided to just make a wrapper for the button + description, I think this is a better solution and works different browsers.
=> Add hover-descriptions to simple-editor control-buttons (add question & finish exploration)

core/controllers/admin.py, core/templates/dev/head/pages/admin/Admin.js, core/templates/dev/head/pages/admin/AdminNavbarDirective.js, core/templates/dev/head/pages/admin/AdminRouterService.js, core/templates/dev/head/pages/admin/AdminRouterServiceSpec.js, core/templates/dev/head/pages/admin/AdminTaskManagerService.js, core/templates/dev/head/pages/admin/AdminTaskManagerServiceSpec.js, core/templates/dev/head/pages/admin/activities_tab/AdminDevModeActivitiesTabDirective.js, core/templates/dev/head/pages/admin/activities_tab/AdminProdModeActivitiesTabDirective.js, core/templates/dev/head/pages/admin/activities_tab/admin_dev_mode_activities_tab_directive.html, core/templates/dev/head/pages/admin/activities_tab/admin_prod_mode_activities_tab_directive.html, core/templates/dev/head/pages/admin/admin.html, core/templates/dev/head/pages/admin/admin_navbar_directive.html, core/templates/dev/head/pages/admin/config_tab/AdminConfigTabDirective.js, core/templates/dev/head/pages/admin/config_tab/admin_config_tab_directive.html, core/templates/dev/head/pages/admin/jobs_tab/AdminJobsTabDirective.js, core/templates/dev/head/pages/admin/jobs_tab/admin_jobs_tab_directive.html, core/templates/dev/head/pages/admin/misc_tab/AdminMiscTabDirective.js, core/templates/dev/head/pages/admin/misc_tab/admin_misc_tab_directive.html
Please see #2669 for detailed information about how the controller was split up. Also, some additional work was done:
- The admin page's `ng-controller` declaration is at the `html` tag rather than a `body` or `div` tag
- I updated the scroll-to-job-output logic to scroll to the top of the job output rather than the bottom of the page (the previous logic did not work so well with large amounts of output)
- I removed all Jinja variables used outside of the controller, which required adding some more variables to the `GLOBALS` array
- Removed the table-style formatting and just used `md-cards` for subsequent directives (they didn't need the table structure anymore, since some of them weren't even really using it)
- Some other minor renames and changes
=> Fix #2669: Split up the admin page controller

core/templates/dev/head/pages/exploration_editor/exploration_editor.html, core/templates/dev/head/pages/exploration_editor/settings_tab/settings_tab.html
This is a proposal for updating the wording of the objective statement so that it's clearer about good description = longer description. We don't want to necessarily encourage people to arbitrarily make their objectives 15 chars or longer, but I think that's going to happen right now, anyway. The current warning basically makes people guess on how to fill out the form; I don't think a lack of clarity is going to help lead to better objective statements.
=> Fix #2667: Update the warning labels for changing the objective to be more clear

core/templates/dev/head/filters.js, core/templates/dev/head/filtersSpec.js
Oppia RTE editor adds style attributes to bold and italics tags, so these have to be removed to preserve the tags on copy and paste from the RTE. Text now goes through two regex filters. Added new tests in filterSpec.
=> Fix #2661: update stripFormatting filter to preserve bold and italics

core/templates/dev/head/pages/exploration_player/conversation_skin_directive.html
This PR fixes #2687 only when the terminal card doesn't contain supplemental interaction.
So the solution is: to use relative position when tutor-card is alone, otherwise use absolute as it was before. 
The fix described in #2687 won't work good with supplemental as well.
The proper solution might be by refactoring layouting, e.g making tutor-card relative position.
=> Fix #2687: Fix tutor card position when viewport is narrow

core/templates/dev/head/pages/collection_player/collection_player.html
=> Fix #2644: In the navbar for the collection learner view, remove the "> Collection" in the breadcrumb.

core/templates/dev/head/pages/exploration_player/conversation_skin_embed_directive.html
also changed the color of the active progressive arrow to white because the default one is green and was not clearly visible.
=> Fix #2679: Hide continue button when pagging back through the cards

core/domain/summary_services.py, core/domain/summary_services_test.py, core/templates/dev/head/components/summary_tile/ExplorationSummaryTileDirective.js
Context: PR #2694 added a fixed footer for explorations, and, as part of doing so, added a human_readable_contributor_summary to the exploration summaries dict. This actually caused a regression in another part of the site: contributor avatars now show up in the top right of exploration summary tiles in the library search page. We discontinued this a while back because there was a lot of bandwidth consumed in transferring lots of image files over the wire (which made the page slow), and also because it looks ugly.
The aim of this PR is to preserve the inclusion of human_readable_contributor_summary, but removing the profile_picture_data_url part of it.
=> Remove thumbnail images that are showing up in exploration summary tiles on the search page.

extensions/dependencies/guppy.html, manifest.json
As discussed in #2754, I have updated the Guppy version from 0.0.2 to 1.0.0
=> Update guppy version from 0.0.2 to 1.0.0 

extensions/interactions/MathExpressionInput/MathExpressionInput.js
PR #2759 introduced a bug, due to which Latex expressions were not evaluated properly. I have tested this for various latex expressions like x^2, x^3, x^2y^2, x^(y^z) and it has worked properly. One thing I would like to mention is that the bug reported in #2755 still exists.
=> Fix bug in math expression input

core/templates/dev/head/pages/header_js_libs.html
=> Fix #2737: Do not wrap math formulae that are less than 500px wide.

core/templates/dev/head/pages/Base.js, core/templates/dev/head/pages/base.html
This is in response to a bug report we received that, when playing an exploration on mobile, it is too easy to open the sidebar, and this interferes with playing the exploration. On closer examination, I am not actually sure why we even need to implement swipe-to-open for the side menu on either mobile or desktop (clicking on the hamburger menu at the top left should be the "standard" way of triggering the 'open' action), so this PR removes this functionality.
=> Remove functionality for opening the sidebar on swipe.

extensions/dependencies/guppy.html, manifest.json
This aims to unblock @Arunabh98's work on #2754, which we ought to get in before the next release this weekend, since we've had several bug reports about the math expression input field.
=> Update guppy to version be6f14.

extensions/dependencies/guppy.html, extensions/interactions/MathExpressionInput/MathExpressionInput.html
I had to use !important in some places because the styles defined in index.css of guppy file appear as inline style attributes which I don't think can be overcome by any other way.
=> Fix #2754: Math expression input box is more clear

core/templates/dev/head/css/oppia.css
On the preferences page, the background color cuts off mid-screen. This also happens in other pages (such as the admin page). Bisecting shows that this is due to a regression due to #2794; this PR fixes that.
=> Fix background color regression.

core/templates/dev/head/pages/exploration_player/SupplementalCardDirective.js, core/templates/dev/head/pages/exploration_player/TutorCardDirective.js, core/templates/dev/head/pages/exploration_player/tutor_card_directive.html
The most important issue was max-width of the future tutor card being arbitrary, thus it was taking whole width, in a result producing smaller height than expected. 
The other fix is when animating to two cards, the interaction instruction part wasn't contributing to the height.
=> Fix some of learning view animation jerking

core/templates/dev/head/pages/exploration_player/ConversationSkinDirective.js, core/templates/dev/head/pages/exploration_player/TutorCardDirective.js, core/templates/dev/head/pages/exploration_player/conversation_skin_directive.html, core/templates/dev/head/pages/exploration_player/tutor_card_directive.html
...and fix animation jerking, both fix are when viewport is narrow.
When viewport is narrow and the tutor card is minimised, it was impossible to click the tutor avatar to maximise, the issue was due to progress dot directive being rendered on top of the tutor avatar.
The animation issue was about disappearing of the future tutor card when the tutor card disappears.
=> Fix learner view: not clickable tutor card icon

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_player/conversation_skin_directive.html
@Oishikatta I have added a bottom margin of 25px to the explorations summary container. Can you verify if its okay?
=> Fix #2832 Add space between footer and summary explorations container

core/controllers/email_dashboard_test.py
Added backend test to ensure that test emails are sent to submitter of query only and not sent to qualifies users of a query.
=> Fix #2840: Add tests to make sure that test email is not sent to query recipients.

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/profile/profile.html
=> Fix #2789: Remove white panel behind exploration cards. Remove 'Portfolio' text.

core/templates/dev/head/pages/header_js_libs.html
This is the easiest way to do it.
See the [original issue](https://github.com/oppia/oppia/issues/2588) for a screenshot and some more.
=> Fix #2588: Make LATEX smaller

core/domain/user_services.py, core/domain/user_services_test.py, core/storage/user/gae_models.py, feconf.py
Add mute boolean properties to ExplorationUserDataModel, add get and set functions to user_services, add two defaults to feconf.
=> Fix #2557 First milestone in email muting

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_editor/ExplorationEditor.js, core/templates/dev/head/pages/exploration_editor/exploration_editor.html
This PR is just fixing the one issue #2716, showing only simple editor tools on the exploration editor for Medium screens (<1024px).
=> Fix #2716: Show only simple editor tools on medium screens per spec

core/controllers/profile.py, core/controllers/profile_test.py, core/domain/email_manager.py, core/domain/email_manager_test.py, core/domain/feedback_services.py, core/domain/feedback_services_test.py, core/domain/user_domain.py, core/domain/user_services.py, core/domain/user_services_test.py, core/storage/user/gae_models.py
Creating new pull request with both commits because I forgot to create local branch before, therefore I had problems with rebasing.
I addressed all comments in #2880
- Created get_multi in ExplorationUserDataModel
- Started using get_multi for all functions with multiple recepients.
- Created UserGlobalPrefs and UserExplorationPrefs domain models.
- Fixed docstrings
=> Fix part of #2557:  Refactoring of email preferences and add functionality to incorporate user's preferences of feedback / suggestions 

.gitignore, scripts/install_prerequisites.sh, scripts/start.sh, scripts/vagrant_lock.sh
`scripts/start.sh` and `scripts/install_prerequisites.sh` now use a lockfile mechanism to keep users from breaking the install under vagrant
Replaced a `return 1` outside of a function call with an `exit 1`
Added new `.lock` file to `.gitignore`
=> Fix #2455: Add lockfile functionality to prevent user error

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/teach/teach.html
The button has been moved on teach page.
Also i noticed unusual height on small screens on about page.
I have fixed it.
=> Fix #2817, Move Call to action button on Teach Page and design fixes on about pages.

scripts/release_info.py
We don't typically include the PR author's name in the changelog, but the release info script includes the name, which necessitates deleting the name later on. Changing the output to be a bullet point with the commit title will streamline the process of compiling the changelog.
=> Update release info output to fit format of changelog

scripts/pre_commit_linter.py
A fix for #2857. I have added an excluded_dirs parameter in the BAD_PATTERNS checker [here](https://github.com/arpan98/oppia/blob/lint-exclude-translatewiki/scripts/pre_commit_linter.py#L88). Should I add it as an empty parameter for the checks other than tabs and spaces as well?
=> Fix #2857: Added excluded_dirs in Lint pattern matching

core/controllers/base_test.py
Fixes #2064 . This walks through the entire root directory and reports any keys in html files which aren't present in en.json.
=> Fix #2064: Add a test for keys present in source code and not in en.json

core/templates/dev/head/components/background/background_banner_directive.html, core/templates/dev/head/components/side_navigation_bar/side_navigation_bar_directive.html, core/templates/dev/head/components/social_buttons/social_buttons_directive.html, core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/top_navigation_bar/top_navigation_bar_directive.html, core/templates/dev/head/pages/about/about.html, core/templates/dev/head/pages/exploration_player/exploration_footer_directive.html, core/templates/dev/head/pages/profile/profile.html, core/templates/dev/head/pages/splash/splash.html, core/templates/dev/head/pages/splash/splash_ah1.html
This PR addresses the following issues from #2862:
- Sign in with Google image, Oppia logo, sidebar social link images need alt attribute that indicates where its link goes. **NOTE:** I noticed that the sidebar social links seem to now be in the footer. Is this changing?
- Books.svg image needs an alt attribute. Since the image is decorative, it can be empty.
- Corner images on exploration collection "cards" needs alt attribute. It can be empty since these images are decorative.
- Exploration background banner has no alt attribute. Since this image is purely decorative, it may be empty.
- Author profile apple image has no alt attribute. Since this image is purely decorative, it may be empty.
- Background banners on About pages have no alt attribute. Since these images are purely …
=> Fix part of #2862: Add alt attributes to images

core/templates/dev/head/pages/exploration_editor/RouterServices.js
A common solution to this problem was to apply applyAsync instead of apply. I tested this, and as far as I found the editor page loads everytime.
=> Fix #2919: Fix the loading of the editor page.

core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/domain/collection/CollectionNodeObjectFactory.js, core/templates/dev/head/pages/about/about.html, core/templates/dev/head/pages/collection_player/collection_player.html, core/templates/dev/head/pages/contact/contact.html, core/templates/dev/head/pages/donate/donate.html, core/templates/dev/head/pages/error/error.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/footer.html, core/templates/dev/head/pages/get_started/get_started.html, core/templates/dev/head/pages/privacy/privacy.html, core/templates/dev/head/pages/profile/profile.html, core/templates/dev/head/pages/terms/terms.html
The following issues are addressed in this PR:
- No H1 on 404 page. First heading is an h4. Then it goes to h3. (Solution: The page now goes from h1 to h2)
- Category headings in the Library (and elsewhere) are h2s and then exploration "card" headings are also h2s, which doesn't provide a great hierarchy. (Solution: Card headings are now h3s)
- No H1 on Exploration page. (Solution: Exploration title in the navbar is now an h1)
- There is no h2 on this page (the about page, not the foundation or credits pages). Skips from h1 to h3. (Solution: Added an h1 with the text "About Oppia"; moved pronunciation pull-right element beneath it)
- At the beginning of the Contact Us page, we skip from h1 to h3. (Solution: Headings before the "Ways you can Help" heading are now h2s)
- There is no h1 on …
=> Fix part of #2862: create logical heading order

core/templates/dev/head/css/oppia.css
The z-index was not present in .oppia-splash-button-container so I've set it to 10 there. Looks like it was only being set in the media query class selector so it already worked fine on certain screen sizes.
=> Fix #2944 : Adjust z-index on browse button.

core/controllers/reader.py, core/controllers/reader_test.py, core/domain/classifier_services.py, core/domain/classifier_services_test.py
This PR solves #2950.
Moved classify_string_classifier_rule and classify to classifier_servies.py and created appropriate tests.
=> Fix #2950: Moved classifier methods and test from reader to classifier_services

core/templates/dev/head/components/attribution_guide/attribution_guide_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/donate/donate.html, core/templates/dev/head/pages/get_started/get_started.html, core/templates/dev/head/pages/teach/teach.html, core/templates/dev/head/pages/terms/terms.html
This PR addresses the following parts of issue #2862:
- Under the CC license image (found on explorations and collection pages) is a link with the text Attribution Guide. This text is covered by the footer and WAVE flags it as having very low contrast. (Solution: Edited CSS to move this link up a bit; also removed the color style. Edited the link href to actually go to the Foundation part of the About page)
- On the About Oppia page, ensure the "I want to Learn" and "I want to teach" links do not have aria roles; These are links masquerading as buttons. (Solution: No change needed; they were fine.)
- On the Get Started page, the "More information about creating explorations can be found here" sentence has the anchor tag on "here". This is considered bad practice. The link text should be …
=> Fix part of #2862: Fix link-related issues

core/templates/dev/head/app.js, core/templates/dev/head/components/create_button/create_activity_button_directive.html, core/templates/dev/head/components/top_navigation_bar/TopNavigationBarDirective.js, core/templates/dev/head/components/top_navigation_bar/top_navigation_bar_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_editor/EditorNavigationDirective.js, core/templates/dev/head/pages/exploration_editor/editor_navigation_directive.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/library/SearchBarDirective.js, core/templates/dev/head/pages/library/search_bar_directive.html, core/tests/protractor_utils/general.js
This PR hides the hamburger menu on most pages at >768px by changing NORMAL_NAVBAR_CUTOFF_WIDTH_PX from 800px to 768px.
This PR uses the $timeout method to run after the navbar has rendered. Still todo look into using a second navbar offscreen to measure.
Example video: https://drive.google.com/open?id=0ByhzG72M0KJuRkNKSzRpa2VSS2M
Overflow on page load is very brief, overflow during resize is up to about 500ms.
=> Fix #2922: Hide hamburger menu >768px, add function to handle navbar overflow

core/templates/dev/head/components/top_navigation_bar/TopNavigationBarDirective.js
NodeList.forEach is not supported in older browsers (#3010), so this PR replaces it with a standard for loop.
=> Fix #3010: Replace nodelist.forEach use with for loop for better compatability.

core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html
Please note: I removed my original repo of oppia and started from a clean slate. I believe adding the additional padding in the internal css should have helped with size limitations.
=> Fix #2940: Adds full objective in the library tiles as popovers

core/templates/dev/head/components/answer_group_editor_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_editor/editor_tab/state_editor_fallbacks.html, core/templates/dev/head/pages/exploration_editor/editor_tab/state_editor_responses.html
Fixes regression in exploration editor from #2927
=> Add nav-block style to enable previous behavior for .nav elements

core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/filters.js, core/templates/dev/head/filtersSpec.js
This PR does the following, in preparation for a hotfix to the live site:
- Truncates objectives in both exploration and collection summary tiles to 40 characters, reverting a change made in https://github.com/oppia/oppia/pull/3038/files#diff-18d8b5b4069371fcbffffdb8e95e57ecR49.
- Removes word-break:break-all on titles, reverting a change that was introduced in #2971.
Reviewers:
- @kevintab95, who reported this issue (since it affects the collection learner view)
- @jblair87, who wrote #3038 
- @jaredsilver, who reviewed #3038
- @nikhilsangwan007, who wrote #2971 
- @kevinlee12, who reviewed #2971 
- @526avijitgupta, who reviewed #2971 
FYI:
- @wxyxinyu, who is doing a post-release hotfix 
Important questions:
(a) @nikhilsangwan007, @kevinlee12, @526avijitgupta: what is the aim of …
=> Standardize truncation of objectives and display of titles on summary tiles.

core/templates/dev/head/components/forms/schema_editors/SchemaBasedListEditorDirective.js, core/templates/dev/head/components/forms/schema_editors/schema_based_list_editor_directive.html, extensions/interactions/SetInput/SetInput.js
Fix https://github.com/oppia/oppia/issues/2814: The add item button is now visible whenever the length of the input field is greater than zero and empty response fields are automatically removed.
=> Fix #2814: Add new items button visibility in the SetInput interaction on mobile

extensions/dependencies/guppy.html, extensions/interactions/MathExpressionInput/MathExpressionInput.js, manifest.json
Updates Guppy and MathExpressionInput.js to match changes in the new version.
=> Fix #3102: Update Guppy to 260da66 to enable better compatibility with non-US keyboards

extensions/objects/templates/filepath_editor.html
Changed the URL of license-term for image insert in editor. Directs to foundation tab of about page.
=> Fix #3094: Changed URL of license-term link in insert image.

core/templates/dev/head/pages/exploration_editor/feedback_tab/FeedbackTab.js
Fix a bug where some state data in the feedback data isn't converted into State objects, causing features in the feedback tab to break. This should allow @arun1595 to continue with #3050 .
=> Convert state dictionary data in FeedbackTab to State objects

core/templates/dev/head/css/oppia.css
fixed bug 3120. 
now ui view in mobile screen size:
=> Fix #3120: Buttons on About page have text overflow on mobile.

core/templates/dev/head/css/oppia.css
Note: Reverts part of #2971. This was supposed to have been fixed in #3067, but for some reason that didn't happen -- apologies!
=> Remove word-break so that lesson titles don't break unnecessarily across lines.

core/templates/dev/head/css/oppia.css
The navbar text items were inheriting the font-size: 0 needed for inline-block to display without extra spacing.
This changes the previous em units to rem units (relative to document root instead of parent).
1.12rem was calculated by taking the previous parent font-size (1.6em) and multiplying by the previous element font size (0.7em).
=> Fix #3129: Make navbar text items visible again by changing to rem.

core/templates/dev/head/components/forms/schema_editors/schema_based_list_editor_directive.html, core/templates/dev/head/components/rating_display.html, core/templates/dev/head/components/share/sharing_links_directive.html, core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html, core/templates/dev/head/components/summary_tile/exploration_summary_tile_directive.html, core/templates/dev/head/components/top_navigation_bar/top_navigation_bar_directive.html, core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/collection_player/collection_player.html, core/templates/dev/head/pages/exploration_player/exploration_footer_directive.html, core/templates/dev/head/pages/exploration_player/exploration_player.html, core/templates/dev/head/pages/exploration_player/information_card_modal.html, core/templates/dev/head/pages/exploration_player/learner_local_nav.html, core/templates/dev/head/pages/exploration_player/progress_dots_directive.html, core/templates/dev/head/pages/library/library.html, core/templates/dev/head/pages/library/search_bar_directive.html, extensions/interactions/ItemSelectionInput/ItemSelectionInput.html
This PR addresses the following issues from #3082:
- Separate out hover and focus styles for the search bar language dropdown and categories dropdown and the language choice select element in the footer. (**Solution:** I did indeed separate the CSS for focus and hover for the search bar dropdown menus. In the case of the language choice element, there was no need.)
- Exploration card metadata (on the library page and the info modal inside of an exploration) is read, but has no context. (**Solution:** I've implemented a specific span element so that icons used in buttons and links have text. [Based off of Nicholas Zakas' blog post.](https://www.nczonline.net/blog/2013/04/01/making-accessible-icon-buttons/))
- The button to scroll through the explorations under a topic heading is just read …
=> Fix part of #3082: Make icon buttons and links screenreader accessible

core/templates/dev/head/css/oppia.css
IE9 does not support translate3d, so the sidebar was stuck permanently displayed.
This adds a -ms prefixed 2d transform which enables the sidebar to function properly in IE9. In small window sizes, the sidebar is usable; in large window sizes it is not displayed.
=> Fix #2828: Add IE9 support for sidebar.

core/templates/dev/head/pages/exploration_editor/exploration_save_and_publish_buttons_directive.html
The `<a> `tag prevented the discard draft tooltip which resulted in same tool tips for both Save and Discard. This is a fix.
#3101
**How to produce the error**?
-  Create a new exploration.
- Hover over the Save Draft, this should pop up **"Save draft"** tooltip. Now hover over Discard Draft button which is a drop down, you will get same tooltip **"Save draft"**
**How I found solution?**
-  #3101 as discussed in this issue I thought its a tooltip CSS/hover problem, but after going through code base there was [special tooltip for Discard draft](https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/pages/exploration_editor/exploration_save_and_publish_buttons_directive.html#L62), where it was assigned near `<a>` tag which caused problem, the hover wasn't registered hence there …
=> Fix #3101: Discard Draft tooltip was not showing up

app.yaml
I have tested this on a production server, and it works! It follows the guidelines in https://cloud.google.com/appengine/docs/standard/python/config/appref .
Note that we need to be very careful to ensure that build files always have slugs, due to the longer cache expiration time.
=> Fix #3162: set expiration explicitly for files in the build directory.

main.py
This was causing a bug in production -- somehow I had no user contribution model even though I was logged in, and this caused a 500 error on accessing oppia.org.
=> Add a check that user contributions for logged in users exist 

core/jobs.py, core/storage/job/gae_models.py
Fix #2394: updated docstrings in the the core/storage/job/gae_models.py  file.
Notes:
1.) I wasn't sure to if I should add a docstring for is_cancelable because it was so simple. If you want me to add it I will gladly. 
2.) While looking through the code I noticed that in core/jobs.py the method:
```
def get_data_for_recent_jobs(recency_msec=DEFAULT_RECENCY_MSEC):
"""Get a list containing data about recent jobs.
This list is arranged in descending order based on the time the job
was enqueued. At most NUM_JOBS_IN_DASHBOARD_LIMIT job descriptions are
returned.
Args:
- recency_secs: the threshold for a recent job, in seconds.
"""
```
The Args section is spelled differently then the actual argument if this is an error I can change this. Also, it doesn't follow the doc string style guide I …
=> Fix #2394: Add useful docstrings to core/storage/job/gae_models.py 

gulpfile.js
The third_party.min.js.map and third_party.min.css.map are generated in the same fodlers as their corresponding files.
=> Fix #3232: Generate source maps into separate files

core/templates/dev/head/css/oppia.css
**NEW PR**
The donation card lacks the background banner alike other pages but the css style properties are inherited from the same causing the top-bottom margin errors in both **desktop** and **mobile** views. 
#2400
**How to Produce Error:**
- In development mode at http://localhost:8181/donate
- You can also view it on web https://www.oppia.org/donate
**Code corrections requested**
`.oppia-donation-card-content-wide {`  
`  margin: 40px  auto 80px;`
`  min-height: 670px;`
`overflow: auto;`
`}`
`@media only screen and (max-width: 1140px) {`
`  .oppia-donation-card-content-wide {`
`  margin-bottom: 90px;`
`  }`
=> Fix #2400: Oppia-donation card margin corrections

core/templates/dev/head/pages/about/about.html, extensions/objects/templates/filepath_editor.html
#3094
**How to produce error**
1. Go to the creator dashboard and edit an exploration.
2. Edit content, and click on the image insert button.
3 Click on "upload a new image"
4. In the "license terms" link (shown below), the link goes to the about page, but not straight to the license terms. The license terms are on the "Foundation" tab.
**Rationale behind the PR code**
Tried anchor tags, alike `ahref="#license" `to the header `<h2 id="license">`. It simply doesn't work as a javascript in [about.html dynamically activates](https://github.com/oppia/oppia/blob/develop/core/templates/dev/head/pages/about/about.html#L492) the tab. Hence modified the Javascript with `||` relation.
Note: This PR points to the **directors** because if **license** is being hyperlinked, the heading is cut off, as …
=> Fix#3094: License terms link in image insert does not work

core/templates/dev/head/pages/exploration_player/tutor_card_directive.html
This change was much simpler than my initial expectation.
While this seems to fix the issue, I think the underlying cause needs more investigation. The cause _may_ be that the exploration player page can be wider than the available screen width (see partly off-screen user icon in screenshot below). However, I haven't been able to replicate that outside of Chrome's devtools. I'll open a new issue and set aside some time for testing later this week.
=> Fix #2870: Limit exploration cards to screen width to maintain centering

core/controllers/collection_editor.py, core/controllers/collection_editor_test.py, core/templates/dev/head/domain/collection/CollectionRightsBackendApiService.js, core/templates/dev/head/domain/collection/CollectionRightsBackendApiServiceSpec.js, core/templates/dev/head/domain/collection/CollectionRightsObjectFactory.js, core/templates/dev/head/domain/collection/CollectionRightsObjectFactorySpec.js, core/templates/dev/head/pages/collection_editor/CollectionEditorNavbarDirective.js, core/templates/dev/head/pages/collection_editor/CollectionEditorStateService.js, core/templates/dev/head/pages/collection_editor/CollectionEditorStateServiceSpec.js, core/templates/dev/head/pages/collection_editor/collection_editor.html, core/templates/dev/head/pages/collection_editor/collection_editor_navbar_directive.html, core/templates/dev/head/pages/collection_editor/settings_tab/CollectionPermissionsCardDirective.js, core/templates/dev/head/pages/collection_editor/settings_tab/collection_permissions_card_directive.html
Convert collections GLOBALS to AJAX calls.
=> Convert GLOBALS to AJAX for collection editor permissions

core/templates/dev/head/pages/collection_editor/collection_editor.html
The collection editor is broken due to missing dependencies. This adds those missing dependencies.
=> Add factory dependencies to collection editor

scripts/setup.sh
When running frontend tests I get this error:
```
npm ERR! peer dep missing: jasmine-core@*, required by karma-jasmine@1.1.0
```
This PR fixes it.
=> Add installation of peer dependency: jasmine-core.

core/domain/classifier_domain.py, core/domain/classifier_registry.py, core/domain/classifier_registry_test.py, core/domain/classifier_services.py, core/domain/classifier_services_test.py, core/tests/performance_tests/lda_string_classifier_performance_test.py, extensions/classifiers/LDAStringClassifier/LDAStringClassifierTest.py
#3297
This PR renames every occurrence of:
- get_all_classifier_ids() to get_all_classifier_algorithm_ids()
- get_classifier_by_id() to get_classifier_by_algorithm_id
PTAL @seanlip @anmolshkl 
Please tell me if I missed something. 
Thanks
=> Fix: #3297 . Renaming Classifier Registry method

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/dashboard/Dashboard.js, core/templates/dev/head/pages/dashboard/dashboard.html, core/templates/dev/head/pages/preferences/Preferences.js, core/templates/dev/head/pages/preferences/preferences.html, core/tests/protractor/subscriptions.js
Due to wrong truncation limit, names overflowed out of the subscription card like this -
The truncation limit has been reduced so that names fit on the card.
=> Fix overflowing of names in the subscription card.

core/templates/dev/head/pages/exploration_editor/EditorNavigationDirective.js, core/templates/dev/head/pages/exploration_editor/editor_navigation_directive.html
#3093
The tooltip "To get help in future click here" doesn't disappear on the click and  causes unintended behavior with profile menu.
**How to produce error?**
1. Login in locally with a new username or just use the test user name with admin panel.
2. Create an exploration. This should pop up the tooltip _"To get help in future click here"_ 
3. Now, click on the profile icon and try to go to any nav element.
**Error**
1. The menu simply disappears and user can't navigate to any page from menu
**Expected behavior**
1. The tooltip must be not cut off. 
2. It should not block user from accessing menu.
**This PR's fix**
=> Fix #3093: Popover of Userhelp button remains constant when the user creates the exploration for the first time.

core/templates/dev/head/css/oppia.css
This makes the navbar usable even when there is an alert box.
=> Fix #2018: make toast z-index lower than navbar z-index

core/domain/collection_jobs_one_off.py, core/domain/collection_jobs_one_off_test.py
The strict migration would fail to migrate collections that e.g. didn't have an objective.
=> Fix collection migration job to use non-strict validation

core/templates/dev/head/pages/donate/donate.html
#3319 
Added ?rel=0 to the video url to avoid related vidoes.
=> Fix #3319: Oppia video at the donation page shows "Related videos" after the video finishes

core/templates/dev/head/pages/exploration_editor/settings_tab/settings_tab.html
#2936
This PR is a suggested fix in the issue above. The exploration description is limited to 100 charaters
=> Fix #2936: Limit the length of goal description in explorations.

core/controllers/editor.py, core/controllers/editor_test.py, core/templates/dev/head/pages/exploration_editor/settings_tab/SettingsTab.js, core/templates/dev/head/pages/exploration_editor/settings_tab/settings_tab.html
What was done ?
'role' variable was passed in GET request to use it for logging information in editor.py
- role variable was attached to the GET request in settings_tab.html and SettingsTab.js in deleteExploration function. 
- Then in editor.py it was checked for cases when role passed is 'admin' and user is not admin, similarly for moderator. It is an overkill as we don't need to pass role to do all this for logging.
How I replaced it ?
- I removed the passing 'role' variable from GET request.
- I gave role variable for editor.py using self.is_admin and self.is_moderator.
=> Refactoring : removed 'role' variable from GET request used in editor.py in delete method

extensions/classifiers/LDAStringClassifier/LDAStringClassifier.py, extensions/classifiers/LDAStringClassifier/LDAStringClassifierTest.py
#3282 
This PR rectifies the validate() function for LDAStringClassifier and also modifies the tests accordingly. 
Since we will be serializing the dict data, we don't need to handle numpy arrays in validate(). There were a couple of issues which had confusions between list_properties and list_of_list_properties. I fixed these issues. 
PTAL @anmolshkl 
Thanks.
=> Fix #3282: Fixes the validate() function for LDAStringClassifier

core/templates/dev/head/components/summary_tile/collection_summary_tile_directive.html
This the fix, for issue #3318. It was simple to fix, the span was not inherited by the class objective which caused alien behavior. Hence repositioned the `span`
**PR's fix:**
=> Fix #3318: Style fixes for collection card in creator dashboard 

core/templates/dev/head/pages/collection_editor/editor_tab/collection_node_creator_directive.html
Change "Add new exploration" to "Create new exploration" to make the distinction with "Add existing exploration" clearer and match our terminology in the NavBar.
=> Fix create exploration button terminology in collection editor.

core/templates/dev/head/css/oppia.css
#2482
**How to reproduce:**
1) Create a exploration on a mobile or desktop
2) Add any interaction like multiple choice or item selection
3) Add atleast one response of a reasonably long length and save it.
4) Vary width if on desktop
**Observed Behavior:**
The answer in responses overflows out of the cards
**Expected behavior:**
The answer should be wrapped to be fit within the cards.
**In the issue:**
**This PR's fix**
=> Fix #2482: Learner's Answers and Oppia's Responses' overflow out of their cards in mobile view 

core/templates/dev/head/components/side_navigation_bar/side_navigation_bar_directive.html
#3355
Modified necessary icons as stated in the issue. 
**PR's commit:**
**Note on Code:**
1. For the contact icon found the relevant icon from the [material icons itself.  ](https://material.io/icons/#ic_mail)
2. The Get started icon (rocket) was not present in the Material icon set as it is very limited. Adopted the font awesome icons, hence added the required `fa` class and font size for it.
=> Fix #3355: Change of Font Awesome Icons for relevancy

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_player/exploration_player.html
#3362
Navbar precision improved as suggested in the issue. 
**PR's commit**
-  Responsive now as expected (500px)
=> Fix #3362 : Improve responsiveness of navbar 

core/templates/dev/head/pages/error/error.html
#3329
The Error 404: Page not found has broken footer, 
**How to produce**
1. Go to any address which is not a page at Oppia, Eg http://localhost:8181/ighiu 
This PR's **commit**
=> Fix #3329: 'Error 404: Page not found' has broken footer

extensions/objects/templates/ImageWithRegionsEditor.js, extensions/objects/templates/image_with_regions_editor.html
Minor changes included in this fix (not originally requested in the bug):
* Changed the labels of new regions to be "Region {index}" instead of just "{index}"
* Changed the colors of selected and non-selected regions for a better look-and-feel. Now non-selected regions are white and translucent and selected ones are blue translucent.
=> Fix #3343: Add trash icon for deleting regions

core/templates/dev/head/css/oppia.css
Made a PR as suggested CSS fix from the issue #3304 
**PR's commit**
=> Fix #3304: Better account for overflowing text on summary cards

extensions/objects/templates/ImageWithRegionsEditor.js, extensions/objects/templates/image_with_regions_editor.html
I've also slipped two additional changes in this PR:
* Make the cursor be 'pointer' when it is over a region (or the region is being moved)
* Fixed some indentation on the template as well as removing an unnecessary </input> closing tag
=> Fix #3344: Have the UI automatically identify draw mode vs drag mode vs resize mode, etc.

cron.yaml
Note that this is (intentionally) a PR into the release branch -- some continuous computations are currently being cleaned up before they have run fully.
=> Clean up MR jobs less frequently.

core/controllers/dashboard.py
PTAL. It turns out that, if explorations subscribed to are later deleted, then there is a mismatch between the list of non-None exploration summaries that are generated and the list of feedback messages returned (which includes exploration summaries that might be None). These two lists were zipped together, causing feedback information to be matched incorrectly to the exploration information.
=> Fix #3259: the number of feedback items in the dashboard is incorrect.

app.yaml
This is probably happening due to the recent GAE upgrade. The fix is mentioned [here](https://github.com/GoogleCloudPlatform/appengine-mapreduce/issues/103#issuecomment-293287529).
@wxyxinyu -- please only merge this once you confirm that it doesn't negatively impact the release process? Thanks!
=> Fix PipelineSetupError when MR jobs are run on the dev server.

core/controllers/dashboard_test.py, core/controllers/library.py, core/controllers/pages.py, core/templates/dev/head/pages/splash/Splash.js, core/templates/dev/head/pages/splash/splash_nv1.html, core/templates/dev/head/pages/splash/splash_nv2.html, core/templates/dev/head/pages/splash/splash_nv3.html, core/templates/dev/head/pages/splash/splash_nv4.html, feconf.py
I apologize this took me so long to get to -- moving three times in two weeks has presented some unexpected time-related challenges.
It's probably already too late to get this into the next release, but if there's some way to squeeze it in so we can start tracking efficacy data alongside the landing pages, it would be much appreciated.
---
These are four new splash pages we will be testing alongside the current splash page in an attempt to increase engagement rates.
Details of the tests, the metrics by which we will evaluate the results, and plans for future improvements to these pages can be found here: https://docs.google.com/spreadsheets/d/1gYx3j-UEoFtHapDh3ZvIYtDnzhoIEAfUZ92vjziZTp0/edit#gid=0
Each splash page (including the current splash page) will receive 20% of traffic to …
=> Testing New Splash Page Variants

core/templates/dev/head/css/oppia.css, core/templates/dev/head/pages/exploration_editor/editor_navigation_directive.html
#1782 
This PR fixes the tooltip button that looks a bit off screen by overriding dynamic CSS styling. PTAL @seanlip . Would this be an issue in screens of varying sizes?
=> Fixes: 1782 - tooltip placement issues

core/templates/dev/head/components/forms/HtmlSelectDirective.js, core/templates/dev/head/components/forms/html_select_directive.html, core/templates/dev/head/pages/exploration_editor/editor_tab/StateInteraction.js, extensions/objects/templates/ImageWithRegionsEditor.js
This PR fixes the display issue - the option selected in the image region customization is displayed correctly.
Also since the default names of the regions were set to be of the form 'Region 1' - the space between Region and the number resulted in a critical error and it would be quite hard for the creator to fix this since normally we expect that the default option is correct.
=> Fix a few bugs in image region interaction.

core/templates/dev/head/pages/splash/splash_nv1.html, core/templates/dev/head/pages/splash/splash_nv2.html, core/templates/dev/head/pages/splash/splash_nv3.html, core/templates/dev/head/pages/splash/splash_nv4.html
~~Note: just found one more oddity -- do not merge yet.~~ Update: this oddity only occurs when a user is on mobile _and_ is signed in _and_ is on a splash page. Probably fine launching with it for now. (Evidently, there's some width difference between the mobile top bar with the sign in button as compared to with the logged-in dropdown, and this results in some weirdness around page width.)
=> Modify styles on new splash pages to better handle certain viewport widths

core/templates/dev/head/pages/exploration_editor/EditorServices.js
Hi @1995YogeshSharma @vojtechjelinek, I discovered another missing dependency due to the template refactor that caused the frontend to break. PTAL.
Also, since this is the second error I found, I am becoming worried that there are more bugs. Please could you double-check the refactoring PRs that have been submitted?
Thanks!
=> Add missing dependency to autosaveInfoModalService.

core/controllers/dashboard.py, core/domain/stats_services.py, core/templates/dev/head/domain/dashboard/DashboardBackendApiServiceSpec.js, core/templates/dev/head/pages/dashboard/Dashboard.js, core/templates/dev/head/pages/dashboard/dashboard.html
Remove unresolved answers from the creator dashboard since:
1. It's too expensive to retrieve a lot of top answers from a list of explorations (known issue with the new storage model)
2. Unresolved answers have a different meaning now, which means they can't be addressed (the unresolved answers section of the exploration editor has been completely removed). We need to enable the training interface before this can happen.
=> Remove unresolved answers from the creator dashboard

core/templates/dev/head/pages/exploration_editor/editor_tab/state_graph_visualization_directive.html
Fix #4542 
**Checklist**
- These should run automatically, but if not, you can manually trigger them locally using `python scripts/pre_commit_linter.py` and `bash scripts/run_frontend_tests.sh`.
- If you're a new contributor, please ask on [Gitter](https://gitter.im/oppia/oppia-chat) for someone to assign a reviewer.
- If you're not sure who the appropriate reviewer is, please assign to the issue's "owner" -- see the "talk-to" label on the issue.
=> Fix #4542: Moves the position of NodeErrorMessage tooltip.

core/templates/dev/head/filters.js, core/templates/dev/head/filtersSpec.js, core/templates/dev/head/services/RteHelperService.js
This PR fixes #4530 by adding filter to remove new lines occuring at the end of the text. 
Tests for the filters have been written as well.
=> Fix #4530 : Fixed extra new lines and whitespaces in Multiple choice Options

extensions/interactions/CodeRepl/directives/CodeRepl.js
**Fix for issue #4562**
The fix is to correct the conditional statements.
=> Fixes issue  #4562 : Overlapping line numbers and text in Code Editor

extensions/interactions/MathExpressionInput/directives/MathExpressionInput.js
Fixes #5260 
**Explanation**
The set_content function applies to the Guppy engine. Here guppyInstance is a prototype of the engine. As defined in guppy.js (line 742). the function import_xml will be used to set the content of the document.
=> Fixes #5260: Unable to type anything in the Math expression input box in mobile
